# Generated by Django 5.0.14 on 2026-05-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0025_fichatecnica_itemfichatecnica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='aliquota_cbs',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_cofins',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_fcp',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_fcp_st',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_ibs_municipal',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_ibs_uf',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_icms',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_icms_st',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_is',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='aliquota_pis',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='classificacao_tributaria_cbs',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='produto',
            name='classificacao_tributaria_ibs',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='produto',
            name='classificacao_tributaria_is',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_beneficio_fiscal_icms',
            field=models.CharField(blank=True, help_text='Codigo de beneficio fiscal quando exigido pela UF', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_cbs',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_ibs',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_is',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='produto',
            name='ex_tipi',
            field=models.CharField(blank=True, help_text='Ex TIPI quando aplicavel', max_length=3),
        ),
        migrations.AddField(
            model_name='produto',
            name='modalidade_bc_icms',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='produto',
            name='modalidade_bc_icms_st',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='produto',
            name='mva_icms_st',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='natureza_receita_pis_cofins',
            field=models.CharField(blank=True, help_text='Usado em regimes como monofasico, aliquota zero ou suspensao', max_length=3),
        ),
        migrations.AddField(
            model_name='produto',
            name='reducao_bc_icms',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='reducao_bc_icms_st',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='reducao_cbs',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='reducao_ibs',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
    ]
