# Generated by Django 6.0.4 on 2026-04-17 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_initial'),
        ('core', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_contagem', 'Em Contagem'), ('em_conferencia', 'Em Conferência'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], db_index=True, default='aberto', max_length=20)),
                ('bloquear_movimentacoes', models.BooleanField(default=False, help_text='Bloqueia movimentações de estoque durante a contagem')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('usuario_fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_fechados', to=settings.AUTH_USER_MODEL)),
                ('usuario_inicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_abertos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'db_table': 'inventarios',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LoteProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_lote', models.CharField(max_length=60)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, db_index=True, help_text='NULL = sem validade', null=True)),
                ('numero_nota_entrada', models.CharField(blank=True, max_length=20)),
                ('ordem_producao_id', models.BigIntegerField(blank=True, help_text='Se o lote foi gerado internamente por uma OP', null=True)),
                ('quantidade_inicial', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantidade_atual', models.DecimalField(db_index=True, decimal_places=3, default=0, max_digits=12)),
                ('custo_unitario', models.DecimalField(decimal_places=4, default=0, help_text='Custo específico deste lote', max_digits=14)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('esgotado', 'Esgotado'), ('vencido', 'Vencido'), ('bloqueado', 'Bloqueado'), ('quarentena', 'Quarentena')], db_index=True, default='ativo', max_length=20)),
                ('motivo_bloqueio', models.TextField(blank=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('fornecedor', models.ForeignKey(blank=True, help_text='Se o lote veio de compra externa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='cadastros.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Lote de Produto',
                'verbose_name_plural': 'Lotes de Produto',
                'db_table': 'lotes_produto',
                'ordering': ['data_validade', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade_sistema', models.DecimalField(decimal_places=3, help_text='Estoque no sistema no momento do inventário', max_digits=12)),
                ('quantidade_contada', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('diferenca', models.DecimalField(blank=True, decimal_places=3, help_text='contada - sistema (positiva = sobra; negativa = falta)', max_digits=12, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('valor_diferenca', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('justificativa', models.TextField(blank=True)),
                ('data_contagem', models.DateTimeField(blank=True, null=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.inventario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='produtos.produto')),
                ('usuario_contagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='estoque.loteproduto')),
            ],
            options={
                'db_table': 'itens_inventario',
                'ordering': ['inventario', 'produto'],
            },
        ),
        migrations.CreateModel(
            name='AlertaVencimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_validade', models.DateField()),
                ('quantidade_em_risco', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('dias_para_vencer', models.SmallIntegerField()),
                ('nivel_risco', models.CharField(choices=[('critico', 'Crítico (D-1)'), ('alto', 'Alto (D-7)'), ('medio', 'Médio (D-30)'), ('baixo', 'Baixo (D-45/60)')], max_length=20)),
                ('notificado_em', models.DateTimeField(blank=True, null=True)),
                ('resolvido', models.BooleanField(db_index=True, default=False)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_vencimento', to='produtos.produto')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_vencimento', to='estoque.loteproduto')),
            ],
            options={
                'verbose_name': 'Alerta de Vencimento',
                'verbose_name_plural': 'Alertas de Vencimento',
                'db_table': 'alertas_vencimento',
                'ordering': ['data_validade'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_operacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('transferencia_saida', 'Transferência (saída)'), ('transferencia_entrada', 'Transferência (entrada)'), ('ajuste_mais', 'Ajuste +'), ('ajuste_menos', 'Ajuste -'), ('inventario', 'Inventário'), ('devolucao_cliente', 'Devolução de Cliente'), ('devolucao_fornecedor', 'Devolução ao Fornecedor'), ('bonificacao', 'Bonificação'), ('baixa_validade', 'Baixa por Validade'), ('uso_proprio', 'Uso Próprio'), ('brinde', 'Brinde'), ('quebra', 'Quebra'), ('producao_entrada', 'Produção (entrada)'), ('producao_saida', 'Produção (saída MP)')], db_index=True, max_length=40)),
                ('documento_tipo', models.CharField(blank=True, choices=[('pedido_venda', 'Pedido de Venda'), ('nfe', 'NF-e'), ('nfce', 'NFC-e'), ('outras_movimentacoes', 'Outras Movimentações'), ('inventario', 'Inventário'), ('transferencia', 'Transferência'), ('ajuste_manual', 'Ajuste Manual'), ('ordem_producao', 'Ordem de Produção')], max_length=30)),
                ('documento_id', models.BigIntegerField(blank=True, null=True)),
                ('documento_numero', models.CharField(blank=True, max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantidade_anterior', models.DecimalField(decimal_places=3, help_text='Snapshot ANTES', max_digits=12)),
                ('quantidade_posterior', models.DecimalField(decimal_places=3, help_text='Snapshot APÓS', max_digits=12)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('custo_medio_anterior', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('custo_medio_posterior', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tara', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('peso_liquido', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('data_movimentacao', models.DateTimeField(db_index=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('filial_destino', models.ForeignKey(blank=True, help_text='Para transferências', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.filial')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.loteproduto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='produtos.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'db_table': 'movimentacoes_estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantidade_reservada', models.DecimalField(decimal_places=3, default=0, help_text='Pedidos confirmados ainda não faturados', max_digits=12)),
                ('quantidade_disponivel', models.DecimalField(decimal_places=3, default=0, help_text='atual - reservada. Mantido pelo service.', max_digits=12)),
                ('custo_medio', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('ultima_entrada', models.DateTimeField(blank=True, null=True)),
                ('ultima_saida', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='core.filial')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoques', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'db_table': 'estoque',
                'indexes': [models.Index(fields=['filial', 'quantidade_disponivel'], name='estoque_filial__051b1b_idx')],
                'unique_together': {('produto', 'filial')},
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='loteproduto',
            index=models.Index(fields=['filial', 'status'], name='lotes_produ_filial__7a9e89_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='loteproduto',
            index=models.Index(fields=['produto', 'status', 'data_validade'], name='lotes_produ_produto_730411_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='loteproduto',
            index=models.Index(fields=['data_validade'], name='lotes_produ_data_va_7107fe_idx'),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='loteproduto',
            unique_together={('produto', 'numero_lote', 'filial')},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='alertavencimento',
            index=models.Index(fields=['filial', 'resolvido', 'data_validade'], name='alertas_ven_filial__8cb78e_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='alertavencimento',
            index=models.Index(fields=['lote', 'nivel_risco'], name='alertas_ven_lote_id_c81f67_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['produto', '-data_movimentacao'], name='movimentaco_produto_ef1859_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['filial', 'tipo_operacao'], name='movimentaco_filial__1d2ec3_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='movimentacaoestoque',
            index=models.Index(fields=['documento_tipo', 'documento_id'], name='movimentaco_documen_fd0dc0_idx'),
                ),
            ],
        ),
    ]
