# Generated by Django 5.2.14 on 2026-06-08 12:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0006_rename_clientes_fi_filial_a9398f_idx_clientes_fi_filial__cb2c0a_idx_and_more'),
        ('core', '0023_permissao_logistica'),
        ('pdv', '0006_vendapdv_sessao_nullable'),
        ('vendas', '0002_compat_legacy_required_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RomaneioCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(db_index=True)),
                ('data', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_carregamento', 'Em carregamento'), ('em_rota', 'Em rota'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=30)),
                ('motorista_nome', models.CharField(blank=True, max_length=120)),
                ('motorista_documento', models.CharField(blank=True, max_length=30)),
                ('veiculo_placa', models.CharField(blank=True, max_length=10)),
                ('veiculo_descricao', models.CharField(blank=True, max_length=100)),
                ('origem', models.CharField(blank=True, max_length=160)),
                ('destino_rota', models.CharField(blank=True, max_length=160)),
                ('observacao', models.TextField(blank=True)),
                ('peso_total_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('volume_total', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios_carga', to=settings.AUTH_USER_MODEL)),
                ('transportadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios_carga', to='cadastros.transportadora')),
            ],
            options={
                'verbose_name': 'Romaneio de Carga',
                'verbose_name_plural': 'Romaneios de Carga',
                'db_table': 'logistica_romaneios_carga',
                'ordering': ['-data', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemRomaneioCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('cliente_nome', models.CharField(max_length=180)),
                ('documento', models.CharField(blank=True, max_length=60)),
                ('endereco_entrega', models.JSONField(blank=True, default=dict)),
                ('status_entrega', models.CharField(choices=[('pendente', 'Pendente'), ('carregado', 'Carregado'), ('entregue', 'Entregue'), ('nao_entregue', 'Nao entregue'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=30)),
                ('volumes', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('peso_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('pedido_venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_romaneio', to='vendas.pedidovenda')),
                ('venda_pdv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_romaneio', to='pdv.vendapdv')),
                ('romaneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='logistica.romaneiocarga')),
            ],
            options={
                'verbose_name': 'Item do Romaneio',
                'verbose_name_plural': 'Itens do Romaneio',
                'db_table': 'logistica_itens_romaneio_carga',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='romaneiocarga',
            index=models.Index(fields=['filial', 'status', '-data'], name='logistica_r_filial__248789_idx'),
        ),
        migrations.AddIndex(
            model_name='romaneiocarga',
            index=models.Index(fields=['filial', '-numero'], name='logistica_r_filial__f8333f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='romaneiocarga',
            unique_together={('filial', 'numero')},
        ),
        migrations.AddIndex(
            model_name='itemromaneiocarga',
            index=models.Index(fields=['romaneio', 'status_entrega'], name='logistica_i_romanei_b8881a_idx'),
        ),
        migrations.AddIndex(
            model_name='itemromaneiocarga',
            index=models.Index(fields=['venda_pdv'], name='logistica_i_venda_p_176b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='itemromaneiocarga',
            index=models.Index(fields=['pedido_venda'], name='logistica_i_pedido__0c488d_idx'),
        ),
    ]
