# Generated by Django 5.2.14 on 2026-06-08 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_rename_clientes_fi_filial_a9398f_idx_clientes_fi_filial__cb2c0a_idx_and_more'),
        ('core', '0023_permissao_logistica'),
        ('logistica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(db_index=True)),
                ('data_solicitacao', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('data_coleta_prevista', models.DateField(blank=True, db_index=True, null=True)),
                ('data_coleta_realizada', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('solicitada', 'Solicitada'), ('programada', 'Programada'), ('coletada', 'Coletada'), ('cancelada', 'Cancelada')], db_index=True, default='rascunho', max_length=30)),
                ('tipo_solicitante', models.CharField(choices=[('cliente', 'Cliente'), ('fornecedor', 'Fornecedor'), ('filial', 'Filial'), ('avulso', 'Avulso')], default='cliente', max_length=20)),
                ('solicitante_nome', models.CharField(blank=True, max_length=180)),
                ('contato_nome', models.CharField(blank=True, max_length=120)),
                ('contato_telefone', models.CharField(blank=True, max_length=30)),
                ('endereco_coleta', models.JSONField(blank=True, default=dict)),
                ('endereco_entrega', models.JSONField(blank=True, default=dict)),
                ('motorista_nome', models.CharField(blank=True, max_length=120)),
                ('veiculo_placa', models.CharField(blank=True, max_length=10)),
                ('volumes', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('peso_total_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_coleta', to='cadastros.cliente')),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_coleta', to='cadastros.fornecedor')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_coleta', to=settings.AUTH_USER_MODEL)),
                ('romaneio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_coleta', to='logistica.romaneiocarga')),
                ('transportadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_coleta', to='cadastros.transportadora')),
            ],
            options={
                'verbose_name': 'Ordem de Coleta',
                'verbose_name_plural': 'Ordens de Coleta',
                'db_table': 'logistica_ordens_coleta',
                'ordering': ['-data_solicitacao', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=220)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unidade', models.CharField(default='UN', max_length=10)),
                ('volumes', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('peso_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='logistica.ordemcoleta')),
            ],
            options={
                'verbose_name': 'Item da Ordem de Coleta',
                'verbose_name_plural': 'Itens da Ordem de Coleta',
                'db_table': 'logistica_itens_ordem_coleta',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='ordemcoleta',
            index=models.Index(fields=['filial', 'status', '-data_solicitacao'], name='logistica_o_filial__07e935_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemcoleta',
            index=models.Index(fields=['filial', 'data_coleta_prevista'], name='logistica_o_filial__f8be6f_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemcoleta',
            index=models.Index(fields=['cliente'], name='logistica_o_cliente_c32885_idx'),
        ),
        migrations.AddIndex(
            model_name='ordemcoleta',
            index=models.Index(fields=['fornecedor'], name='logistica_o_fornece_50882b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ordemcoleta',
            unique_together={('filial', 'numero')},
        ),
        migrations.AddIndex(
            model_name='itemordemcoleta',
            index=models.Index(fields=['ordem'], name='logistica_i_ordem_i_7bc70b_idx'),
        ),
    ]
