# Generated by Django 5.2.14 on 2026-06-08 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_rename_clientes_fi_filial_a9398f_idx_clientes_fi_filial__cb2c0a_idx_and_more'),
        ('core', '0023_permissao_logistica'),
        ('logistica', '0002_ordemcoleta_itemordemcoleta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(db_index=True)),
                ('data_emissao', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('emitido', 'Emitido'), ('em_transito', 'Em transito'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=30)),
                ('modal', models.CharField(choices=[('rodoviario', 'Rodoviario'), ('aereo', 'Aereo'), ('aquaviario', 'Aquaviario'), ('ferroviario', 'Ferroviario')], default='rodoviario', max_length=20)),
                ('motorista_nome', models.CharField(blank=True, max_length=120)),
                ('motorista_documento', models.CharField(blank=True, max_length=30)),
                ('veiculo_placa', models.CharField(blank=True, max_length=10)),
                ('veiculo_descricao', models.CharField(blank=True, max_length=100)),
                ('cidade_origem', models.CharField(blank=True, max_length=100)),
                ('uf_origem', models.CharField(blank=True, max_length=2)),
                ('cidade_destino', models.CharField(blank=True, max_length=100)),
                ('uf_destino', models.CharField(blank=True, max_length=2)),
                ('percurso', models.TextField(blank=True)),
                ('qtd_documentos', models.PositiveIntegerField(default=0)),
                ('volumes', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('peso_total_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestos_carga', to=settings.AUTH_USER_MODEL)),
                ('romaneio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestos_carga', to='logistica.romaneiocarga')),
                ('transportadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestos_carga', to='cadastros.transportadora')),
            ],
            options={
                'verbose_name': 'Manifesto de Carga',
                'verbose_name_plural': 'Manifestos de Carga',
                'db_table': 'logistica_manifestos_carga',
                'ordering': ['-data_emissao', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoManifestoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(choices=[('nfe', 'NF-e'), ('nfce', 'NFC-e'), ('cte', 'CT-e'), ('nfse', 'NFS-e'), ('outro', 'Outro')], default='nfe', max_length=20)),
                ('numero_documento', models.CharField(max_length=60)),
                ('serie', models.CharField(blank=True, max_length=20)),
                ('chave_acesso', models.CharField(blank=True, db_index=True, max_length=80)),
                ('remetente_nome', models.CharField(blank=True, max_length=180)),
                ('destinatario_nome', models.CharField(blank=True, max_length=180)),
                ('cidade_origem', models.CharField(blank=True, max_length=100)),
                ('uf_origem', models.CharField(blank=True, max_length=2)),
                ('cidade_destino', models.CharField(blank=True, max_length=100)),
                ('uf_destino', models.CharField(blank=True, max_length=2)),
                ('volumes', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('peso_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('manifesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='logistica.manifestocarga')),
            ],
            options={
                'verbose_name': 'Documento do Manifesto',
                'verbose_name_plural': 'Documentos do Manifesto',
                'db_table': 'logistica_documentos_manifesto_carga',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='manifestocarga',
            index=models.Index(fields=['filial', 'status', '-data_emissao'], name='logistica_m_filial__012b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestocarga',
            index=models.Index(fields=['filial', '-numero'], name='logistica_m_filial__a656ea_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestocarga',
            index=models.Index(fields=['romaneio'], name='logistica_m_romanei_23eb3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='manifestocarga',
            unique_together={('filial', 'numero')},
        ),
        migrations.AddIndex(
            model_name='documentomanifestocarga',
            index=models.Index(fields=['manifesto'], name='logistica_d_manifes_7dc639_idx'),
        ),
        migrations.AddIndex(
            model_name='documentomanifestocarga',
            index=models.Index(fields=['tipo_documento', 'numero_documento'], name='logistica_d_tipo_do_49b967_idx'),
        ),
    ]
