# Generated by Django 6.0.4 on 2026-06-08 13:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_rename_clientes_fi_filial_a9398f_idx_clientes_fi_filial__cb2c0a_idx_and_more'),
        ('core', '0024_cte'),
        ('logistica', '0003_manifestocarga_documentomanifestocarga_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CTe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(db_index=True)),
                ('numero_cte', models.CharField(blank=True, db_index=True, max_length=20)),
                ('serie', models.CharField(blank=True, default='1', max_length=10)),
                ('chave_acesso', models.CharField(blank=True, db_index=True, max_length=44)),
                ('data_emissao', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_digitacao', 'Em digitacao'), ('autorizado', 'Autorizado'), ('cancelado', 'Cancelado'), ('denegado', 'Denegado')], db_index=True, default='rascunho', max_length=20)),
                ('modal', models.CharField(choices=[('rodoviario', 'Rodoviario'), ('aereo', 'Aereo'), ('aquaviario', 'Aquaviario'), ('ferroviario', 'Ferroviario'), ('dutoviario', 'Dutoviario'), ('multimodal', 'Multimodal')], default='rodoviario', max_length=20)),
                ('tipo_cte', models.CharField(choices=[('normal', 'Normal'), ('complemento', 'Complemento de valores'), ('anulacao', 'Anulacao de valores'), ('substituto', 'Substituto')], default='normal', max_length=20)),
                ('cfop', models.CharField(blank=True, max_length=10)),
                ('natureza_operacao', models.CharField(blank=True, max_length=120)),
                ('tomador', models.CharField(choices=[('remetente', 'Remetente'), ('destinatario', 'Destinatario'), ('expedidor', 'Expedidor'), ('recebedor', 'Recebedor'), ('outros', 'Outros')], default='remetente', max_length=20)),
                ('remetente_nome', models.CharField(blank=True, max_length=180)),
                ('remetente_documento', models.CharField(blank=True, max_length=20)),
                ('destinatario_nome', models.CharField(blank=True, max_length=180)),
                ('destinatario_documento', models.CharField(blank=True, max_length=20)),
                ('cidade_origem', models.CharField(blank=True, max_length=100)),
                ('uf_origem', models.CharField(blank=True, max_length=2)),
                ('cidade_destino', models.CharField(blank=True, max_length=100)),
                ('uf_destino', models.CharField(blank=True, max_length=2)),
                ('percurso', models.TextField(blank=True)),
                ('motorista_nome', models.CharField(blank=True, max_length=120)),
                ('motorista_documento', models.CharField(blank=True, max_length=30)),
                ('veiculo_placa', models.CharField(blank=True, max_length=10)),
                ('veiculo_descricao', models.CharField(blank=True, max_length=100)),
                ('volumes', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('peso_total_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('valor_carga', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_pedagio', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_outros', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('protocolo_autorizacao', models.CharField(blank=True, max_length=60)),
                ('data_autorizacao', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctes', to=settings.AUTH_USER_MODEL)),
                ('transportadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctes', to='cadastros.transportadora')),
            ],
            options={
                'verbose_name': 'CT-e',
                'verbose_name_plural': 'CT-es',
                'db_table': 'logistica_cte',
                'ordering': ['-data_emissao', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCTe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(choices=[('nfe', 'NF-e'), ('nfce', 'NFC-e'), ('cte', 'CT-e anterior'), ('nfse', 'NFS-e'), ('outro', 'Outro')], default='nfe', max_length=20)),
                ('numero_documento', models.CharField(max_length=60)),
                ('serie', models.CharField(blank=True, max_length=20)),
                ('chave_acesso', models.CharField(blank=True, db_index=True, max_length=80)),
                ('emitente_nome', models.CharField(blank=True, max_length=180)),
                ('volumes', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('peso_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('cte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='logistica.cte')),
            ],
            options={
                'verbose_name': 'Documento do CT-e',
                'verbose_name_plural': 'Documentos do CT-e',
                'db_table': 'logistica_documentos_cte',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='cte',
            index=models.Index(fields=['filial', 'status', '-data_emissao'], name='logistica_c_filial__9d3e21_idx'),
        ),
        migrations.AddIndex(
            model_name='cte',
            index=models.Index(fields=['filial', '-numero'], name='logistica_c_filial__4078bc_idx'),
        ),
        migrations.AddIndex(
            model_name='cte',
            index=models.Index(fields=['chave_acesso'], name='logistica_c_chave_a_0c90e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cte',
            unique_together={('filial', 'numero')},
        ),
        migrations.AddIndex(
            model_name='documentocte',
            index=models.Index(fields=['cte'], name='logistica_d_cte_id_31c18c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentocte',
            index=models.Index(fields=['tipo_documento', 'numero_documento'], name='logistica_d_tipo_do_53fb3a_idx'),
        ),
    ]
