# Generated by Django 6.0.4 on 2026-06-08 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0009_motorista_add_cep_bairro_numero"),
        ("core", "0024_cte"),
        ("logistica", "0004_cte"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoExpedicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.PositiveIntegerField(db_index=True)),
                (
                    "data_pedido",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "data_previsao_entrega",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("data_expedicao", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("em_separacao", "Em Separação"),
                            ("separado", "Separado"),
                            ("expedido", "Expedido"),
                            ("entregue", "Entregue"),
                            ("cancelado", "Cancelado"),
                        ],
                        db_index=True,
                        default="aberto",
                        max_length=20,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("contato_nome", models.CharField(blank=True, max_length=120)),
                ("contato_telefone", models.CharField(blank=True, max_length=30)),
                ("endereco_entrega", models.JSONField(blank=True, default=dict)),
                ("motorista_nome", models.CharField(blank=True, max_length=120)),
                ("veiculo_placa", models.CharField(blank=True, max_length=10)),
                (
                    "volumes",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "peso_total_kg",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("observacao", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos_expedicao",
                        to="cadastros.cliente",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_expedicao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "romaneio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_expedicao",
                        to="logistica.romaneiocarga",
                    ),
                ),
                (
                    "transportadora",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_expedicao",
                        to="cadastros.transportadora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Expedição",
                "verbose_name_plural": "Pedidos de Expedição",
                "db_table": "logistica_pedidos_expedicao",
                "ordering": ["-data_pedido", "-numero"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedidoExpedicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("produto_codigo", models.CharField(blank=True, max_length=60)),
                ("produto_nome", models.CharField(max_length=220)),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                ("unidade", models.CharField(default="UN", max_length=10)),
                (
                    "volumes",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "peso_kg",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status_item",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("separado", "Separado"),
                            ("expedido", "Expedido"),
                            ("cancelado", "Cancelado"),
                        ],
                        db_index=True,
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="logistica.pedidoexpedicao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do Pedido de Expedição",
                "verbose_name_plural": "Itens do Pedido de Expedição",
                "db_table": "logistica_itens_pedido_expedicao",
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="pedidoexpedicao",
            index=models.Index(
                fields=["filial", "status", "-data_pedido"],
                name="logistica_p_filial__91a7b4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pedidoexpedicao",
            index=models.Index(
                fields=["filial", "-numero"], name="logistica_p_filial__e58a32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pedidoexpedicao",
            index=models.Index(
                fields=["cliente"], name="logistica_p_cliente_7425f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pedidoexpedicao",
            index=models.Index(
                fields=["filial", "data_previsao_entrega"],
                name="logistica_p_filial__f5f814_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pedidoexpedicao",
            unique_together={("filial", "numero")},
        ),
        migrations.AddIndex(
            model_name="itempedidoexpedicao",
            index=models.Index(
                fields=["pedido"], name="logistica_i_pedido__655f03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itempedidoexpedicao",
            index=models.Index(
                fields=["pedido", "status_item"], name="logistica_i_pedido__ac2a14_idx"
            ),
        ),
    ]
