# Generated by Django 6.0.4 on 2026-04-17 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_initial'),
        ('core', '0001_initial'),
        ('estoque', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(db_index=True, max_length=20)),
                ('motivo', models.CharField(choices=[('defeito', 'Produto com defeito'), ('nao_conformidade', 'Não conformidade'), ('arrependimento', 'Arrependimento do cliente'), ('atraso', 'Atraso na entrega'), ('erro_pedido', 'Erro no pedido'), ('outros', 'Outros')], max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada'), ('finalizada', 'Finalizada')], default='rascunho', max_length=20)),
                ('data_devolucao', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devolucoes_venda',
                'ordering': ['-data_devolucao'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_item', models.SmallIntegerField(default=1)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantidade_atendida', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade efetivamente separada/faturada', max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('percentual_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('custo_unitario_snapshot', models.DecimalField(decimal_places=4, default=0, help_text='Custo médio do produto no momento da venda', max_digits=14)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='produtos.produto')),
            ],
            options={
                'db_table': 'itens_pedido_venda',
                'ordering': ['pedido', 'numero_item'],
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('retornar_ao_estoque', models.BooleanField(default=True, help_text='Se True, retorna ao estoque; se False (produto danificado), apenas registra a devolução financeira')),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.devolucaovenda')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='estoque.loteproduto')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='vendas.itempedidovenda')),
            ],
            options={
                'db_table': 'itens_devolucao',
            },
        ),
        migrations.CreateModel(
            name='PedidoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_pedido', models.CharField(db_index=True, max_length=20)),
                ('tipo', models.CharField(choices=[('orcamento', 'Orçamento'), ('pedido', 'Pedido'), ('venda_balcao', 'Venda Balcão'), ('consignacao', 'Consignação'), ('remessa', 'Remessa')], default='pedido', max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('confirmado', 'Confirmado'), ('em_separacao', 'Em Separação'), ('faturado', 'Faturado'), ('parcialmente_faturado', 'Parcialmente Faturado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado'), ('devolvido', 'Devolvido')], db_index=True, default='rascunho', max_length=30)),
                ('origem', models.CharField(choices=[('pdv', 'PDV'), ('balcao', 'Balcão'), ('externo', 'Externo'), ('api', 'API'), ('ecommerce', 'E-commerce'), ('whatsapp', 'WhatsApp'), ('telefone', 'Telefone')], default='balcao', max_length=20)),
                ('prioridade', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('vip', 'VIP')], default='normal', max_length=10)),
                ('endereco_entrega_avulso', models.JSONField(blank=True, null=True)),
                ('data_emissao', models.DateTimeField(db_index=True)),
                ('data_validade_orcamento', models.DateField(blank=True, null=True)),
                ('data_entrega_prevista', models.DateField(blank=True, null=True)),
                ('data_entrega_realizada', models.DateField(blank=True, null=True)),
                ('modalidade_frete', models.SmallIntegerField(choices=[(0, '0 - CIF (por conta do emitente)'), (1, '1 - FOB (por conta do destinatário)'), (2, '2 - Terceiros'), (3, '3 - Remetente'), (4, '4 - Destinatário'), (9, '9 - Sem frete')], default=0)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_outras_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_st', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_icms', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_pis', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
                ('observacao_interna', models.TextField(blank=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='cadastros.cliente')),
                ('endereco_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.clienteendereco')),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='cadastros.representante')),
                ('tabela_preco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='produtos.tabelapreco')),
                ('transportadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.transportadora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_criados', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.veiculotransportadora')),
            ],
            options={
                'verbose_name': 'Pedido de Venda',
                'verbose_name_plural': 'Pedidos de Venda',
                'db_table': 'pedidos_venda',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.AddField(
            model_name='itempedidovenda',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.pedidovenda'),
        ),
        migrations.AddField(
            model_name='devolucaovenda',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='vendas.pedidovenda'),
        ),
        migrations.CreateModel(
            name='SeparacaoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='separacoes', to='vendas.pedidovenda')),
                ('usuario_separador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='separacoes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'separacoes_pedido',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ItemSeparacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade_separada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='separacoes', to='vendas.itempedidovenda')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.loteproduto')),
                ('separacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.separacaopedido')),
            ],
            options={
                'db_table': 'itens_separacao',
            },
        ),
        migrations.AddIndex(
            model_name='pedidovenda',
            index=models.Index(fields=['filial', 'status'], name='pedidos_ven_filial__b7128e_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidovenda',
            index=models.Index(fields=['cliente', '-data_emissao'], name='pedidos_ven_cliente_8ad1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='itempedidovenda',
            index=models.Index(fields=['pedido', 'numero_item'], name='itens_pedid_pedido__ffa6a0_idx'),
        ),
    ]
