from django.core.management.base import BaseCommand
from django.db import connection


class Command(BaseCommand):
    help = "Garante as tabelas de parametros de qualidade no deploy."

    def handle(self, *args, **options):
        existing_tables = set(connection.introspection.table_names())
        required_tables = {"filiais", "produtos", "categorias_produto"}
        missing = required_tables - existing_tables
        if missing:
            self.stdout.write(self.style.WARNING(
                f"Qualidade ignorada: tabelas base ausentes: {', '.join(sorted(missing))}"
            ))
            return

        vendor = connection.vendor
        with connection.cursor() as cursor:
            if vendor == "postgresql":
                if "parametros_qualidade_produtos" not in existing_tables:
                    cursor.execute("""
                        CREATE TABLE IF NOT EXISTS parametros_qualidade_produtos (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            filial_id BIGINT NOT NULL REFERENCES filiais(id) DEFERRABLE INITIALLY DEFERRED,
                            produto_id BIGINT NOT NULL REFERENCES produtos(id) DEFERRABLE INITIALLY DEFERRED,
                            ativo BOOLEAN NOT NULL DEFAULT TRUE,
                            etapa VARCHAR(30) NOT NULL DEFAULT 'produto_acabado',
                            nome_parametro VARCHAR(60) NOT NULL,
                            tipo_valor VARCHAR(20) NOT NULL DEFAULT 'numero',
                            unidade_medida VARCHAR(10) NOT NULL DEFAULT '',
                            valor_minimo NUMERIC(10, 3) NULL,
                            valor_maximo NUMERIC(10, 3) NULL,
                            valor_ideal NUMERIC(10, 3) NULL,
                            valor_texto_ideal VARCHAR(120) NOT NULL DEFAULT '',
                            opcoes JSONB NOT NULL DEFAULT '[]'::jsonb,
                            obrigatorio BOOLEAN NOT NULL DEFAULT TRUE,
                            CONSTRAINT parametros_qualidade_produtos_unique
                                UNIQUE (filial_id, produto_id, etapa, nome_parametro)
                        )
                    """)
                    cursor.execute("""
                        CREATE INDEX IF NOT EXISTS parametros_qualidade_produtos_created_at_idx
                        ON parametros_qualidade_produtos (created_at)
                    """)
                    cursor.execute("""
                        CREATE INDEX IF NOT EXISTS parametros_qualidade_produtos_filial_id_idx
                        ON parametros_qualidade_produtos (filial_id)
                    """)
                    cursor.execute("""
                        CREATE INDEX IF NOT EXISTS parametros_qualidade_produtos_produto_id_idx
                        ON parametros_qualidade_produtos (produto_id)
                    """)
                if "parametros_qualidade_categorias" not in existing_tables:
                    cursor.execute("""
                        CREATE TABLE IF NOT EXISTS parametros_qualidade_categorias (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            filial_id BIGINT NOT NULL REFERENCES filiais(id) DEFERRABLE INITIALLY DEFERRED,
                            categoria_id BIGINT NOT NULL REFERENCES categorias_produto(id) DEFERRABLE INITIALLY DEFERRED,
                            ativo BOOLEAN NOT NULL DEFAULT TRUE,
                            etapa VARCHAR(30) NOT NULL DEFAULT 'produto_acabado',
                            nome_parametro VARCHAR(60) NOT NULL,
                            tipo_valor VARCHAR(20) NOT NULL DEFAULT 'numero',
                            unidade_medida VARCHAR(10) NOT NULL DEFAULT '',
                            valor_minimo NUMERIC(10, 3) NULL,
                            valor_maximo NUMERIC(10, 3) NULL,
                            valor_ideal NUMERIC(10, 3) NULL,
                            valor_texto_ideal VARCHAR(120) NOT NULL DEFAULT '',
                            opcoes JSONB NOT NULL DEFAULT '[]'::jsonb,
                            obrigatorio BOOLEAN NOT NULL DEFAULT TRUE,
                            CONSTRAINT parametros_qualidade_categorias_unique
                                UNIQUE (filial_id, categoria_id, etapa, nome_parametro)
                        )
                    """)
                    cursor.execute("""
                        CREATE INDEX IF NOT EXISTS parametros_qualidade_categorias_created_at_idx
                        ON parametros_qualidade_categorias (created_at)
                    """)
                    cursor.execute("""
                        CREATE INDEX IF NOT EXISTS parametros_qualidade_categorias_filial_id_idx
                        ON parametros_qualidade_categorias (filial_id)
                    """)
                    cursor.execute("""
                        CREATE INDEX IF NOT EXISTS parametros_qualidade_categorias_categoria_id_idx
                        ON parametros_qualidade_categorias (categoria_id)
                    """)
            else:
                if "parametros_qualidade_produtos" not in existing_tables:
                    cursor.execute("""
                        CREATE TABLE IF NOT EXISTS parametros_qualidade_produtos (
                            id INTEGER PRIMARY KEY AUTOINCREMENT,
                            created_at DATETIME NOT NULL,
                            updated_at DATETIME NOT NULL,
                            filial_id BIGINT NOT NULL REFERENCES filiais(id),
                            produto_id BIGINT NOT NULL REFERENCES produtos(id),
                            ativo BOOL NOT NULL DEFAULT 1,
                            etapa VARCHAR(30) NOT NULL DEFAULT 'produto_acabado',
                            nome_parametro VARCHAR(60) NOT NULL,
                            tipo_valor VARCHAR(20) NOT NULL DEFAULT 'numero',
                            unidade_medida VARCHAR(10) NOT NULL DEFAULT '',
                            valor_minimo DECIMAL(10, 3) NULL,
                            valor_maximo DECIMAL(10, 3) NULL,
                            valor_ideal DECIMAL(10, 3) NULL,
                            valor_texto_ideal VARCHAR(120) NOT NULL DEFAULT '',
                            opcoes TEXT NOT NULL DEFAULT '[]',
                            obrigatorio BOOL NOT NULL DEFAULT 1,
                            UNIQUE (filial_id, produto_id, etapa, nome_parametro)
                        )
                    """)
                if "parametros_qualidade_categorias" not in existing_tables:
                    cursor.execute("""
                        CREATE TABLE IF NOT EXISTS parametros_qualidade_categorias (
                            id INTEGER PRIMARY KEY AUTOINCREMENT,
                            created_at DATETIME NOT NULL,
                            updated_at DATETIME NOT NULL,
                            filial_id BIGINT NOT NULL REFERENCES filiais(id),
                            categoria_id BIGINT NOT NULL REFERENCES categorias_produto(id),
                            ativo BOOL NOT NULL DEFAULT 1,
                            etapa VARCHAR(30) NOT NULL DEFAULT 'produto_acabado',
                            nome_parametro VARCHAR(60) NOT NULL,
                            tipo_valor VARCHAR(20) NOT NULL DEFAULT 'numero',
                            unidade_medida VARCHAR(10) NOT NULL DEFAULT '',
                            valor_minimo DECIMAL(10, 3) NULL,
                            valor_maximo DECIMAL(10, 3) NULL,
                            valor_ideal DECIMAL(10, 3) NULL,
                            valor_texto_ideal VARCHAR(120) NOT NULL DEFAULT '',
                            opcoes TEXT NOT NULL DEFAULT '[]',
                            obrigatorio BOOL NOT NULL DEFAULT 1,
                            UNIQUE (filial_id, categoria_id, etapa, nome_parametro)
                        )
                    """)

        self.stdout.write(self.style.SUCCESS("Tabelas de qualidade OK"))
