# Generated by Django 6.0.4 on 2026-04-17 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('estoque', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, help_text='Código interno da ficha', max_length=30)),
                ('descricao', models.CharField(max_length=150)),
                ('versao', models.CharField(default='1.0', max_length=10)),
                ('quantidade_produzida', models.DecimalField(decimal_places=3, default=1, help_text='Quantidade de produto acabado gerada pela execução da ficha', max_digits=12)),
                ('tempo_producao_minutos', models.IntegerField(default=0, help_text='Tempo estimado de produção em minutos')),
                ('custo_mao_obra_padrao', models.DecimalField(decimal_places=2, default=0, help_text='Custo de MO padrão por execução', max_digits=14)),
                ('custo_indireto_padrao', models.DecimalField(decimal_places=2, default=0, help_text='Custos indiretos alocados (energia, depreciação etc.)', max_digits=14)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativa', 'Ativa'), ('inativa', 'Inativa')], default='rascunho', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('produto_acabado', models.ForeignKey(help_text='Produto que será gerado ao executar esta ficha', on_delete=django.db.models.deletion.PROTECT, related_name='producao_fichas_tecnicas', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
                'db_table': 'producao_fichas_tecnicas',
                'ordering': ['produto_acabado', '-versao'],
                'unique_together': {('produto_acabado', 'versao', 'filial')},
            },
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(db_index=True, max_length=20)),
                ('quantidade_planejada', models.DecimalField(decimal_places=3, help_text='Quantidade de produto acabado prevista', max_digits=12)),
                ('quantidade_produzida', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade efetivamente gerada (informada no encerramento)', max_digits=12)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aberta', 'Aberta'), ('em_producao', 'Em Produção'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], db_index=True, default='rascunho', max_length=20)),
                ('data_inicio_prevista', models.DateTimeField(blank=True, null=True)),
                ('data_fim_prevista', models.DateTimeField(blank=True, null=True)),
                ('data_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('data_fim_real', models.DateTimeField(blank=True, null=True)),
                ('rendimento', models.DecimalField(decimal_places=2, default=0, help_text='% de rendimento (produzida / planejada) * 100', max_digits=5)),
                ('peso_entrada_mp', models.DecimalField(decimal_places=3, default=0, help_text='Peso total de matéria-prima consumida', max_digits=12)),
                ('peso_saida_produzido', models.DecimalField(decimal_places=3, default=0, help_text='Peso total do produto acabado gerado', max_digits=12)),
                ('custo_materia_prima', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('custo_mao_obra', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('custo_indireto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('custo_unitario_lote', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('ficha_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='producao.fichatecnica')),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('lote_gerado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_origem', to='estoque.loteproduto')),
                ('produto_acabado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_producao', to='produtos.produto')),
                ('usuario_abertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops_abertas', to=settings.AUTH_USER_MODEL)),
                ('usuario_encerramento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_encerradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordem de Produção',
                'verbose_name_plural': 'Ordens de Produção',
                'db_table': 'ordens_producao',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerdaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(choices=[('processo', 'Processo'), ('qualidade', 'Qualidade'), ('vencimento', 'Vencimento'), ('outros', 'Outros')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('valor', models.DecimalField(decimal_places=2, default=0, help_text='Valor monetário da perda (qtd × custo unitário)', max_digits=14)),
                ('descricao', models.TextField(blank=True)),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perdas', to='producao.ordemproducao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='produtos.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perdas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perdas_producao',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemFichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantidade', models.DecimalField(decimal_places=4, help_text='Quantidade consumida por execução completa da ficha', max_digits=12)),
                ('perda_prevista', models.DecimalField(decimal_places=2, default=0, help_text='% de perda esperada (ex: 5 = 5%)', max_digits=5)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='producao.fichatecnica')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='produtos.produto')),
            ],
            options={
                'db_table': 'producao_itens_ficha_tecnica',
                'ordering': ['ficha', 'materia_prima'],
                'unique_together': {('ficha', 'materia_prima')},
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='ordemproducao',
            index=models.Index(fields=['filial', 'status'], name='ordens_prod_filial__46a9a6_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='ordemproducao',
            index=models.Index(fields=['produto_acabado', 'status'], name='ordens_prod_produto_a9436e_idx'),
                ),
            ],
        ),
    ]
