# Generated by Django 5.0.14 on 2026-05-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0002_perda_producao_schema_atual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perdaproducao',
            options={'ordering': ['-created_at'], 'verbose_name': 'Perda de produção', 'verbose_name_plural': 'Perdas de produção'},
        ),
        migrations.AlterField(
            model_name='perdaproducao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
