# Generated by Django 5.0.14 on 2026-04-28 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('core', '0001_initial'),
        ('produtos', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocustoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_custo', to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='historicocustoproduto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicoprecovenda',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.filial'),
        ),
        migrations.AddField(
            model_name='historicoprecovenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_preco', to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='historicoprecovenda',
            name='tabela_preco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.tabelapreco'),
        ),
        migrations.AddField(
            model_name='historicoprecovenda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integracaoexterna',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integracoes', to='core.filial'),
        ),
        migrations.AddField(
            model_name='logacessoanalytics',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_logacesso_filial', to='core.filial'),
        ),
        migrations.AddField(
            model_name='logacessoanalytics',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_acessos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logerro',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filial'),
        ),
        migrations.AddField(
            model_name='logerro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logsistemaanalytics',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_logsistema_filial', to='core.filial'),
        ),
        migrations.AddField(
            model_name='logsistemaanalytics',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_logsistema_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moduloativo',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_ativos', to='core.filial'),
        ),
        migrations.AddField(
            model_name='travaperiodo',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travaperiodo',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travas_periodo', to='core.filial'),
        ),
        migrations.AddField(
            model_name='webhookconfiguracao',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.filial'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='webhook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='analytics.webhookconfiguracao'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracaosistema',
            unique_together={('filial', 'chave')},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='logsistemaanalytics',
                    index=models.Index(fields=['data_hora'], name='log_sistema_data_ho_c05b35_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='logsistemaanalytics',
                    index=models.Index(fields=['tabela_afetada', 'registro_id'], name='log_sistema_tabela__e400aa_idx'),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='moduloativo',
            unique_together={('filial', 'modulo')},
        ),
    ]
