# Generated by Django 5.0.14 on 2026-05-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                model_name='logsistemaanalytics',
                new_name='analytics_l_data_ho_21d17f_idx',
                old_name='log_sistema_data_ho_c05b35_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                model_name='logsistemaanalytics',
                new_name='analytics_l_tabela__c5f1cd_idx',
                old_name='log_sistema_tabela__e400aa_idx',
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='historicoprecovenda',
            name='tabela_preco',
        ),
        migrations.AlterField(
            model_name='integracaoexterna',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='integracaoexterna',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
