# Generated by Django 6.0.4 on 2026-04-17 05:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razao_social', models.CharField(max_length=150)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'CNPJ deve conter 14 dígitos numéricos.')])),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20)),
                ('regime_tributario', models.CharField(choices=[('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real'), ('mei', 'MEI')], max_length=20)),
                ('codigo_regime_tributario', models.SmallIntegerField(help_text='1=SN 2=SN_excesso 3=Normal')),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=60)),
                ('bairro', models.CharField(blank=True, max_length=80)),
                ('cidade', models.CharField(blank=True, max_length=80)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('codigo_municipio_ibge', models.CharField(blank=True, max_length=7)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=120)),
                ('site', models.URLField(blank=True, max_length=120)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('certificado_digital_path', models.CharField(blank=True, max_length=500)),
                ('certificado_senha_hash', models.CharField(blank=True, max_length=255)),
                ('certificado_validade', models.DateField(blank=True, null=True)),
                ('ambiente_nfe', models.SmallIntegerField(choices=[(1, 'Produção'), (2, 'Homologação')], default=2)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razao_social', models.CharField(max_length=150)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'CNPJ deve conter 14 dígitos numéricos.')])),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20)),
                ('is_matriz', models.BooleanField(default=False)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=60)),
                ('bairro', models.CharField(blank=True, max_length=80)),
                ('cidade', models.CharField(blank=True, max_length=80)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('codigo_municipio_ibge', models.CharField(blank=True, max_length=7)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=120)),
                ('ambiente_nfe', models.SmallIntegerField(choices=[(1, 'Produção'), (2, 'Homologação')], default=2)),
                ('serie_nfe', models.SmallIntegerField(default=1)),
                ('serie_nfce', models.SmallIntegerField(default=1)),
                ('serie_nfse', models.SmallIntegerField(default=1)),
                ('proximo_numero_nfe', models.BigIntegerField(default=1)),
                ('proximo_numero_nfce', models.BigIntegerField(default=1)),
                ('proximo_numero_nfse', models.BigIntegerField(default=1)),
                ('focusnfe_token', models.CharField(blank=True, max_length=100)),
                ('focusnfe_ambiente', models.SmallIntegerField(default=2)),
                ('certificado_digital_path', models.CharField(blank=True, max_length=500)),
                ('certificado_senha_hash', models.CharField(blank=True, max_length=255)),
                ('certificado_validade', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filiais', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiais',
                'db_table': 'filiais',
                'ordering': ['empresa', 'razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pin_code', models.CharField(blank=True, max_length=6)),
                ('pin_exige_supervisor', models.BooleanField(default=False)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('ip_ultimo_acesso', models.GenericIPAddressField(blank=True, null=True)),
                ('tentativas_login_falhas', models.SmallIntegerField(default=0)),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.empresa')),
                ('filial', models.ForeignKey(blank=True, help_text='Filial padrão do usuário', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.filial')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('senha_errada', 'Senha Errada'), ('bloqueio', 'Bloqueio'), ('pin_pdv', 'PIN PDV')], max_length=20)),
                ('ip_acesso', models.GenericIPAddressField(blank=True, null=True)),
                ('device_serial', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('sucesso', models.BooleanField()),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_acesso',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=60)),
                ('acao', models.CharField(choices=[('criar', 'Criar'), ('editar', 'Editar'), ('excluir', 'Excluir'), ('cancelar', 'Cancelar'), ('aprovar', 'Aprovar'), ('rejeitar', 'Rejeitar'), ('acessar', 'Acessar'), ('exportar', 'Exportar')], max_length=30)),
                ('tabela_afetada', models.CharField(blank=True, max_length=60)),
                ('registro_id', models.BigIntegerField(blank=True, null=True)),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('ip_acesso', models.GenericIPAddressField(blank=True, null=True)),
                ('device_serial', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filial')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_sistema',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Perfil de Acesso',
                'verbose_name_plural': 'Perfis de Acesso',
                'db_table': 'perfis_acesso',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.perfilacesso'),
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('vendas', 'Vendas'), ('estoque', 'Estoque'), ('financeiro', 'Financeiro'), ('fiscal', 'Fiscal'), ('config', 'Configurações'), ('relatorios', 'Relatórios'), ('pdv', 'PDV'), ('producao', 'Produção'), ('compras', 'Compras'), ('cadastros', 'Cadastros'), ('produtos', 'Produtos')], max_length=60)),
                ('pode_ver', models.BooleanField(default=False)),
                ('pode_criar', models.BooleanField(default=False)),
                ('pode_editar', models.BooleanField(default=False)),
                ('pode_excluir', models.BooleanField(default=False)),
                ('pode_cancelar', models.BooleanField(default=False)),
                ('pode_aprovar', models.BooleanField(default=False)),
                ('pode_exportar', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='core.perfilacesso')),
            ],
            options={
                'db_table': 'permissoes',
                'ordering': ['perfil', 'modulo'],
            },
        ),
        migrations.CreateModel(
            name='SessaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=255)),
                ('refresh_token_hash', models.CharField(blank=True, max_length=255)),
                ('ip_acesso', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_serial', models.CharField(blank=True, max_length=255)),
                ('data_expiracao', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessoes_usuario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='filial',
            index=models.Index(fields=['empresa', 'ativo'], name='filiais_empresa_19da41_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='logsistema',
            index=models.Index(fields=['tabela_afetada', 'registro_id'], name='log_sistema_tabela__e400aa_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='logsistema',
            index=models.Index(fields=['usuario', '-data_hora'], name='log_sistema_usuario_71c609_idx'),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='perfilacesso',
            unique_together={('empresa', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='permissao',
            unique_together={('perfil', 'modulo')},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='sessaousuario',
            index=models.Index(fields=['usuario', 'ativo'], name='sessoes_usu_usuario_7b4f5a_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='sessaousuario',
            index=models.Index(fields=['token_hash'], name='sessoes_usu_token_h_178d05_idx'),
                ),
            ],
        ),
    ]
