# Generated by Codex on 2026-05-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.producao.constants.enums


def normalizar_tipo_perda(apps, schema_editor):
    PerdaProducao = apps.get_model('producao', 'PerdaProducao')
    PerdaProducao.objects.filter(tipo_perda='outros').update(tipo_perda='processo')


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        ('producao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApontamentoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etapa', models.CharField(choices=apps.producao.constants.enums.EtapaProducao.choices, max_length=40)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True)),
                ('quantidade_produzida_etapa', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantidade_perdida_etapa', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('parametros_processo', models.JSONField(blank=True, default=dict, help_text='{"temperatura":-18,"brix":12.5,"ph":3.8,"umidade":12,"pressao":5.2}')),
                ('equipamento_utilizado', models.CharField(blank=True, max_length=60)),
                ('observacao', models.TextField(blank=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apontamentos', to=settings.AUTH_USER_MODEL)),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='producao.ordemproducao')),
            ],
            options={
                'verbose_name': 'Apontamento',
                'verbose_name_plural': 'Apontamentos',
                'db_table': 'apontamentos_producao',
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.RenameField(
            model_name='perdaproducao',
            old_name='categoria',
            new_name='tipo_perda',
        ),
        migrations.RenameField(
            model_name='perdaproducao',
            old_name='descricao',
            new_name='motivo_detalhado',
        ),
        migrations.RenameField(
            model_name='perdaproducao',
            old_name='valor',
            new_name='impacto_custo',
        ),
        migrations.RenameField(
            model_name='perdaproducao',
            old_name='usuario',
            new_name='usuario_registro',
        ),
        migrations.RunPython(normalizar_tipo_perda, migrations.RunPython.noop),
        migrations.AddField(
            model_name='perdaproducao',
            name='apontamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producao.apontamentoproducao'),
        ),
        migrations.AddField(
            model_name='perdaproducao',
            name='etapa',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='perdaproducao',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.loteproduto'),
        ),
        migrations.AddField(
            model_name='perdaproducao',
            name='perda_evitavel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perdaproducao',
            name='unidade_medida',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='perdaproducao',
            name='impacto_custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='perdaproducao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto'),
        ),
        migrations.AlterField(
            model_name='perdaproducao',
            name='tipo_perda',
            field=models.CharField(choices=apps.producao.constants.enums.TipoPerda.choices, max_length=30),
        ),
        migrations.AlterField(
            model_name='perdaproducao',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='perdaproducao',
            options={'ordering': ['-created_at'], 'verbose_name': 'Perda de producao', 'verbose_name_plural': 'Perdas de producao'},
        ),
    ]
