# Generated by Django 5.0.14 on 2026-05-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_politicareplicacaofilial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicareplicacaofilial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='politicareplicacaofilial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
