# Generated by Django 5.0.14 on 2026-05-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_registroauditoria'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registroauditoria',
            new_name='registros_a_modulo_a33783_idx',
            old_name='registros_a_modulo_5a598c_idx',
        ),
        migrations.RenameIndex(
            model_name='registroauditoria',
            new_name='registros_a_objeto__d31499_idx',
            old_name='registros_a_objeto__7b5349_idx',
        ),
        migrations.RenameIndex(
            model_name='registroauditoria',
            new_name='registros_a_relacio_9886af_idx',
            old_name='registros_a_relacio_7c2b86_idx',
        ),
        migrations.RenameIndex(
            model_name='registroauditoria',
            new_name='registros_a_usuario_d8fb67_idx',
            old_name='registros_a_usuario_92638f_idx',
        ),
        migrations.RenameIndex(
            model_name='registroauditoria',
            new_name='registros_a_filial__983dd1_idx',
            old_name='registros_a_filial__c73f5f_idx',
        ),
    ]
