# Generated by Django 5.2.14 on 2026-05-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_certificado_digital"),
        ("core", "0018_parametros_certificado_digital"),
    ]

    operations = []
