# Generated by Django 6.0.4 on 2026-05-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20260522_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrossistema',
            name='certificado_digital',
            field=models.FileField(blank=True, help_text='Arquivo do certificado digital A1 (.pfx ou .p12).', null=True, upload_to='sistema/certificados/'),
        ),
        migrations.AlterField(
            model_name='parametrossistema',
            name='senha_certificado',
            field=models.CharField(blank=True, help_text='Senha do certificado digital. Use apenas em ambiente controlado.', max_length=255),
        ),
    ]
