# Generated by Django 5.2.14 on 2026-06-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_parametros_certificado_digital"),
        ("core", "0020_alter_parametrossistema_certificado_digital_and_more"),
    ]

    operations = []
