# Generated by Django 5.2.14 on 2026-06-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_politicareplicacaofilial_created_at_and_more"),
        ("core", "0021_merge_20260602_1124"),
    ]

    operations = []
