# Generated by Django 5.2.14 on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_merge_20260602_1750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissao",
            name="modulo",
            field=models.CharField(
                choices=[
                    ("vendas", "Vendas"),
                    ("estoque", "Estoque"),
                    ("financeiro", "Financeiro"),
                    ("fiscal", "Fiscal"),
                    ("config", "Configurações"),
                    ("relatorios", "Relatórios"),
                    ("pdv", "PDV"),
                    ("producao", "Produção"),
                    ("qualidade", "Qualidade"),
                    ("compras", "Compras"),
                    ("cadastros", "Cadastros"),
                    ("produtos", "Produtos"),
                    ("logistica", "Logistica"),
                ],
                max_length=60,
            ),
        ),
    ]
