# Generated by Django 6.0.4 on 2026-06-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_permissao_logistica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametrodocumentofiscal',
            options={'ordering': ['parametros', 'tipo_documento'], 'verbose_name': 'Parâmetro de Documento Fiscal', 'verbose_name_plural': 'Parâmetros de Documentos Fiscais'},
        ),
        migrations.AlterModelOptions(
            name='parametrossistema',
            options={'verbose_name': 'Parâmetros do Sistema', 'verbose_name_plural': 'Parâmetros do Sistema'},
        ),
        migrations.AlterField(
            model_name='parametrodocumentofiscal',
            name='ambiente',
            field=models.SmallIntegerField(choices=[(1, 'Produção'), (2, 'Homologação')], default=2),
        ),
        migrations.AlterField(
            model_name='parametrodocumentofiscal',
            name='habilitado',
            field=models.BooleanField(default=False, help_text='Quando ativo, o documento fica disponível para emissão.'),
        ),
    ]
