# Generated by Django 5.2.13 on 2026-04-18 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_initial'),
        ('core', '0001_initial'),
        ('estoque', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaNF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_nf', models.CharField(db_index=True, max_length=20)),
                ('serie_nf', models.CharField(default='1', max_length=5)),
                ('chave_acesso_nf', models.CharField(blank=True, db_index=True, help_text='Chave de 44 dígitos da NF-e do fornecedor', max_length=44)),
                ('data_emissao_nf', models.DateField()),
                ('data_entrada', models.DateTimeField(db_index=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('devolucao', 'Devolução de Cliente'), ('transferencia', 'Transferência')], default='entrada', max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('processando', 'Processando'), ('efetivada', 'Efetivada'), ('cancelada', 'Cancelada')], db_index=True, default='rascunho', max_length=20)),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_seguro', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_outras_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_icms', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_icms_st', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_pis', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_cofins', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_efetivacao', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_nf', to='cadastros.fornecedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_criadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_efetivacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_efetivadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de NF',
                'verbose_name_plural': 'Entradas de NF',
                'db_table': 'entradas_nf',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_item', models.SmallIntegerField(default=1)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantidade_recebida', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade efetivamente recebida em entradas de NF', max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('prazo_entrega_dias', models.SmallIntegerField(default=0)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='produtos.produto')),
            ],
            options={
                'db_table': 'itens_pedido_compra',
                'ordering': ['pedido', 'numero_item'],
            },
        ),
        migrations.CreateModel(
            name='ItemEntradaNF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_item', models.SmallIntegerField(default=1)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_icms', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('numero_lote', models.CharField(blank=True, max_length=60)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.entradanf')),
                ('lote_gerado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='estoque.loteproduto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='produtos.produto')),
                ('item_pedido_compra', models.ForeignKey(blank=True, help_text='Link ao item do pedido original (para abater quantidade)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_entrada', to='compras.itempedidocompra')),
            ],
            options={
                'db_table': 'itens_entrada_nf',
                'ordering': ['entrada', 'numero_item'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_pedido', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('aprovado', 'Aprovado'), ('enviado_fornecedor', 'Enviado ao Fornecedor'), ('confirmado_fornecedor', 'Confirmado pelo Fornecedor'), ('parcialmente_recebido', 'Parcialmente Recebido'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=30)),
                ('data_emissao', models.DateTimeField(db_index=True)),
                ('data_entrega_prevista', models.DateField(blank=True, null=True)),
                ('data_entrega_realizada', models.DateField(blank=True, null=True)),
                ('modalidade_frete', models.SmallIntegerField(choices=[(0, '0 - CIF (por conta do emitente)'), (1, '1 - FOB (por conta do destinatário)'), (2, '2 - Terceiros'), (9, '9 - Sem frete')], default=0)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_outras_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_compra_aprovados', to=settings.AUTH_USER_MODEL)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='cadastros.fornecedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'db_table': 'pedidos_compra',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.AddField(
            model_name='itempedidocompra',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.pedidocompra'),
        ),
        migrations.AddField(
            model_name='entradanf',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='compras.pedidocompra'),
        ),
        migrations.CreateModel(
            name='AvaliacaoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('data_real', models.DateField()),
                ('dias_atraso', models.IntegerField(default=0, help_text='Negativo = entregou antes. Positivo = atrasou.')),
                ('entregue_no_prazo', models.BooleanField(default=True)),
                ('nota_pontualidade', models.SmallIntegerField(default=5)),
                ('nota_qualidade', models.SmallIntegerField(default=5, help_text='Pode ser ajustada manualmente posteriormente')),
                ('nota_geral', models.DecimalField(decimal_places=2, default=5, max_digits=3)),
                ('observacao', models.TextField(blank=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='cadastros.fornecedor')),
                ('entrada_nf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='compras.entradanf')),
                ('pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='compras.pedidocompra')),
            ],
            options={
                'verbose_name': 'Avaliação de Fornecedor',
                'verbose_name_plural': 'Avaliações de Fornecedor',
                'db_table': 'avaliacoes_fornecedor',
                'ordering': ['-data_real'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['filial', 'status'], name='pedidos_com_filial__0b0046_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='pedidocompra',
            index=models.Index(fields=['fornecedor', '-data_emissao'], name='pedidos_com_fornece_c5e46c_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='entradanf',
            index=models.Index(fields=['filial', 'status'], name='entradas_nf_filial__783dfb_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='entradanf',
            index=models.Index(fields=['chave_acesso_nf'], name='entradas_nf_chave_a_95676e_idx'),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='entradanf',
            unique_together={('fornecedor', 'numero_nf', 'serie_nf', 'filial')},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='avaliacaofornecedor',
            index=models.Index(fields=['fornecedor', '-data_real'], name='avaliacoes__fornece_6fb548_idx'),
                ),
            ],
        ),
    ]
