# Generated by Django 5.0.14 on 2026-04-28 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('estoque', '0001_initial'),
        ('financeiro', '0001_initial'),
        ('pdv', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dreconsolidado',
            name='linha_producao',
            field=models.ForeignKey(blank=True, help_text='NULL = consolidado de todas as linhas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.linhaproducao'),
        ),
        migrations.AddField(
            model_name='drecentrocusto',
            name='dre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_custo', to='financeiro.dreconsolidado'),
        ),
        migrations.AddField(
            model_name='extratobancario',
            name='conta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extratos', to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='extratobancario',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.filial'),
        ),
        migrations.AddField(
            model_name='conciliacaobancaria',
            name='extrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliacoes', to='financeiro.extratobancario'),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pagamento', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.formapagamento'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.formapagamento'),
        ),
        migrations.AddField(
            model_name='idempotenciafiscal',
            name='documento_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.documentofiscal'),
        ),
        migrations.AddField(
            model_name='idempotenciafiscal',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filial'),
        ),
        migrations.AddField(
            model_name='inutilizacaonumeracao',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.filial'),
        ),
        migrations.AddField(
            model_name='inutilizacaonumeracao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemdocumentofiscal',
            name='documento_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financeiro.documentofiscal'),
        ),
        migrations.AddField(
            model_name='itemdocumentofiscal',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.loteproduto'),
        ),
        migrations.AddField(
            model_name='itemdocumentofiscal',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='logintegracaofiscal',
            name='documento_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.documentofiscal'),
        ),
        migrations.AddField(
            model_name='logintegracaofiscal',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.filial'),
        ),
        migrations.AddField(
            model_name='naturezaoperacao',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='natureza_operacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.naturezaoperacao'),
        ),
        migrations.AddField(
            model_name='nfedadosexportacao',
            name='documento_fiscal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_exportacao', to='financeiro.documentofiscal'),
        ),
        migrations.AddField(
            model_name='nfedadosimportacao',
            name='documento_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_importacao', to='financeiro.documentofiscal'),
        ),
        migrations.AddField(
            model_name='nfseconfiguracaomunicipio',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filial'),
        ),
        migrations.AddField(
            model_name='pixcobranca',
            name='conta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='pixcobranca',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pix_cobrancas', to='core.filial'),
        ),
        migrations.AddField(
            model_name='planocontas',
            name='conta_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhas', to='financeiro.planocontas'),
        ),
        migrations.AddField(
            model_name='planocontas',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_contas', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='drecentrocusto',
            name='plano_contas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.planocontas'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='plano_contas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.planocontas'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='plano_contas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.planocontas'),
        ),
        migrations.AddField(
            model_name='remessabancaria',
            name='conta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='remessabancaria',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.filial'),
        ),
        migrations.AddField(
            model_name='remessabancaria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boleto',
            name='remessa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.remessabancaria'),
        ),
        migrations.AddField(
            model_name='retornobancario',
            name='conta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.contabancaria'),
        ),
        migrations.AddField(
            model_name='retornobancario',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.filial'),
        ),
        migrations.AddField(
            model_name='retornobancario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boleto',
            name='retorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.retornobancario'),
        ),
        migrations.AddField(
            model_name='tefconfiguracao',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdv.caixa'),
        ),
        migrations.AddField(
            model_name='tefconfiguracao',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tef_configuracoes', to='core.filial'),
        ),
        migrations.AddField(
            model_name='teftransacao',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.filial'),
        ),
        migrations.AddField(
            model_name='teftransacao',
            name='sessao_pdv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdv.sessaopdv'),
        ),
        migrations.AddField(
            model_name='teftransacao',
            name='venda_pdv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdv.vendapdv'),
        ),
        migrations.AlterUniqueTogether(
            name='classefiscal',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='classefiscalaliquota',
            index=models.Index(fields=['classe_fiscal', 'uf_destino', 'vigencia_inicio'], name='classe_fisc_classe__8b1e29_idx'),
        ),
        migrations.AddIndex(
            model_name='dreconsolidado',
            index=models.Index(fields=['filial', '-competencia'], name='dre_consoli_filial__df72ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dreconsolidado',
            unique_together={('filial', 'competencia', 'linha_producao')},
        ),
        migrations.AddIndex(
            model_name='extratobancario',
            index=models.Index(fields=['conta_bancaria', 'data_lancamento'], name='extratos_ba_conta_b_f364e2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofiscal',
            index=models.Index(fields=['filial', 'tipo_documento', 'status'], name='documentos__filial__75bf8a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofiscal',
            index=models.Index(fields=['chave'], name='documentos__chave_cc0b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofiscal',
            index=models.Index(fields=['origem_tipo', 'origem_id'], name='documentos__origem__77d4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['filial', 'status', 'data_vencimento'], name='contas_rece_filial__a10f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['filial', 'cliente'], name='contas_rece_filial__183777_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['filial', 'status', 'data_vencimento'], name='contas_paga_filial__00611e_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['filial', 'fornecedor'], name='contas_paga_filial__dda319_idx'),
        ),
    ]
