# Generated by Django 5.0.14 on 2026-05-27 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_parametros_certificado_digital'),
        ('financeiro', '0003_rename_classe_fisc_classe__8b1e29_idx_financeiro__classe__045763_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_custo', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Centro de custo',
                'verbose_name_plural': 'Centros de custo',
                'db_table': 'centros_custo',
                'ordering': ['codigo', 'nome'],
                'indexes': [models.Index(fields=['empresa', 'ativo'], name='centro_custo_empresa_ativo_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='centrocusto',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_centro_custo_codigo_empresa'),
        ),
    ]
