# Generated by Django 5.2.14 on 2026-05-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0003_formapagamento_empresa"),
        (
            "financeiro",
            "0003_rename_classe_fisc_classe__8b1e29_idx_financeiro__classe__045763_idx_and_more",
        ),
    ]

    operations = []
