# Generated by Codex on 2026-05-28

import django.db.models.deletion
from django.db import migrations, models


def vincular_formas_pagamento_filial(apps, schema_editor):
    FormaPagamento = apps.get_model("financeiro", "FormaPagamento")
    Filial = apps.get_model("core", "Filial")

    for forma in FormaPagamento.objects.filter(filial__isnull=True).iterator():
        filial = (
            Filial.objects
            .filter(empresa_id=forma.empresa_id)
            .order_by("id")
            .first()
        )
        if filial:
            forma.filial_id = filial.id
            forma.save(update_fields=["filial"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_parametros_certificado_digital"),
        ("financeiro", "0004_centrocusto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formapagamento",
            name="filial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formas_pagamento",
                to="core.filial",
            ),
        ),
        migrations.RunPython(vincular_formas_pagamento_filial, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="formapagamento",
            index=models.Index(fields=["filial", "ativo"], name="forma_pagto_filial_ativo_idx"),
        ),
    ]
