# Generated by Django 6.0.4 on 2026-05-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_credito_cliente'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creditocliente',
            new_name='financeiro__filial__2a5b32_idx',
            old_name='fin_credcli_filial_idx',
        ),
    ]
