# Generated by Django 5.2.14 on 2026-06-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0006_credito_cliente"),
        ("financeiro", "0007_planoncontas_empresa_conta_pai"),
    ]

    operations = []
