# Generated by Django 5.2.14 on 2026-06-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_merge_20260602_1124'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creditocliente',
            new_name='financeiro__filial__2a5b32_idx',
            old_name='fin_credcli_filial_idx',
        ),
    ]
