# Generated by Django 6.0.4 on 2026-05-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_movimentacao_documento_estorno_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertavencimento',
            name='nivel_risco',
            field=models.CharField(choices=[('d1', 'Urgente — 1 dia'), ('d7', 'Crítico — 7 dias'), ('d30', 'Alto — 30 dias'), ('d60', 'Médio — 60 dias'), ('d90', 'Atenção — 90 dias'), ('d180', 'Aviso — 180 dias'), ('critico', 'Crítico (legado)'), ('alto', 'Alto (legado)'), ('medio', 'Médio (legado)'), ('baixo', 'Baixo (legado)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo_operacao',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('transferencia_saida', 'Transferência (saída)'), ('transferencia_entrada', 'Transferência (entrada)'), ('ajuste_mais', 'Ajuste +'), ('ajuste_menos', 'Ajuste -'), ('inventario', 'Inventário'), ('devolucao_cliente', 'Devolução de Cliente'), ('devolucao_fornecedor', 'Devolução ao Fornecedor'), ('bonificacao', 'Bonificação'), ('baixa_validade', 'Baixa por Validade'), ('uso_proprio', 'Uso Próprio'), ('brinde', 'Brinde'), ('quebra', 'Quebra'), ('producao_entrada', 'Produção (entrada)'), ('producao_saida', 'Produção (saída MP)'), ('roubo', 'Roubo/Furto'), ('perda', 'Perda'), ('deterioracao', 'Deterioração')], db_index=True, max_length=40),
        ),
    ]
