# Generated by Django 5.0.14 on 2026-05-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_movimentacao_documento_estorno_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertavencimento',
            name='nivel_risco',
            field=models.CharField(choices=[('d1', 'Urgente - 1 dia'), ('d7', 'Critico - 7 dias'), ('d30', 'Alto - 30 dias'), ('d60', 'Medio - 60 dias'), ('d90', 'Atencao - 90 dias'), ('d180', 'Aviso - 180 dias'), ('critico', 'Critico (legado)'), ('alto', 'Alto (legado)'), ('medio', 'Medio (legado)'), ('baixo', 'Baixo (legado)')], max_length=20),
        ),
    ]
