# Generated by Django 5.2.14 on 2026-06-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0003_alter_alertavencimento_nivel_risco"),
        ("estoque", "0003_alter_alertavencimento_nivel_risco_and_more"),
    ]

    operations = []
