# Generated by Django 6.0.4 on 2026-04-17 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('categoria_pai', models.ForeignKey(blank=True, help_text='Categoria pai (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='produtos.categoriaproduto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_produto', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produto',
                'db_table': 'categorias_produto',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'categoria_pai', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ClasseFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=100)),
                ('cst_icms_padrao', models.CharField(blank=True, max_length=3)),
                ('csosn_padrao', models.CharField(blank=True, help_text='Para Simples Nacional', max_length=3)),
                ('cst_pis_padrao', models.CharField(blank=True, max_length=2)),
                ('cst_cofins_padrao', models.CharField(blank=True, max_length=2)),
                ('cst_ipi_padrao', models.CharField(blank=True, max_length=2)),
                ('pis_cofins_monofasico', models.BooleanField(default=False)),
                ('ipi_suspenso', models.BooleanField(default=False, help_text='IPI suspenso em exportações')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_fiscais', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Classe Fiscal',
                'verbose_name_plural': 'Classes Fiscais',
                'db_table': 'classes_fiscais',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='NaturezaOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('venda', 'Venda'), ('compra', 'Compra'), ('devolucao_cliente', 'Devolução de Cliente'), ('devolucao_fornecedor', 'Devolução ao Fornecedor'), ('transferencia', 'Transferência'), ('exportacao', 'Exportação'), ('importacao', 'Importação'), ('brinde', 'Brinde'), ('uso_proprio', 'Uso Próprio'), ('baixa_validade', 'Baixa por Validade'), ('ajuste', 'Ajuste')], max_length=30)),
                ('cfop_dentro_estado', models.CharField(max_length=5)),
                ('cfop_fora_estado', models.CharField(blank=True, max_length=5)),
                ('cfop_exportacao', models.CharField(blank=True, max_length=5)),
                ('gera_nfe', models.BooleanField(default=True)),
                ('gera_nfce', models.BooleanField(default=False)),
                ('movimenta_estoque', models.BooleanField(default=True)),
                ('movimenta_financeiro', models.BooleanField(default=True)),
                ('tipo_movimentacao_estoque', models.CharField(blank=True, choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naturezas_operacao', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Natureza de Operação',
                'verbose_name_plural': 'Naturezas de Operação',
                'db_table': 'naturezas_operacao',
                'ordering': ['descricao'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'CREATE TABLE IF NOT EXISTS "linhas_producao" ('
                        '"id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, '
                        '"created_at" timestamp with time zone NOT NULL, '
                        '"updated_at" timestamp with time zone NOT NULL, '
                        '"ativo" boolean NOT NULL, '
                        '"nome" varchar(60) NOT NULL, '
                        '"prefixo_lote" varchar(2) NOT NULL UNIQUE, '
                        '"prefixo_op" varchar(6) NOT NULL UNIQUE, '
                        '"descricao_processo" text NOT NULL, '
                        '"meta_rendimento_percentual" numeric(5, 2) NOT NULL, '
                        '"meta_perda_maxima_percentual" numeric(5, 2) NOT NULL, '
                        '"taxa_hora_maquina" numeric(14, 4) NOT NULL, '
                        '"taxa_hora_mod" numeric(14, 4) NOT NULL, '
                        '"cor_identificacao" varchar(7) NOT NULL, '
                        '"icone" varchar(30) NOT NULL, '
                        '"empresa_id" bigint NOT NULL REFERENCES "empresas" ("id") DEFERRABLE INITIALLY DEFERRED'
                        ');'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='LinhaProducao',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('ativo', models.BooleanField(default=True)),
                        ('nome', models.CharField(help_text='Polpa de Frutas | Massas Alimenticias | Embalagens', max_length=60)),
                        ('prefixo_lote', models.CharField(help_text='PF | MA | EB', max_length=2, unique=True)),
                        ('prefixo_op', models.CharField(help_text='OP-PF- | OP-MA- | OP-EB-', max_length=6, unique=True)),
                        ('descricao_processo', models.TextField(blank=True)),
                        ('meta_rendimento_percentual', models.DecimalField(decimal_places=2, help_text='Polpa>75 | Massas>85 | Embalagens>92', max_digits=5)),
                        ('meta_perda_maxima_percentual', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                        ('taxa_hora_maquina', models.DecimalField(decimal_places=4, help_text='Custo/hora para rateio de CIF', max_digits=14)),
                        ('taxa_hora_mod', models.DecimalField(decimal_places=4, help_text='Custo/hora de mao de obra direta', max_digits=14)),
                        ('cor_identificacao', models.CharField(default='#3b82f6', help_text='Hex (UI)', max_length=7)),
                        ('icone', models.CharField(default='industria', max_length=30)),
                        ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas_producao', to='core.empresa')),
                    ],
                    options={
                        'verbose_name': 'Linha de Producao',
                        'verbose_name_plural': 'Linhas de Producao',
                        'db_table': 'linhas_producao',
                        'ordering': ['nome'],
                    },
                ),
            ],
        ),
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('varejo', 'Varejo'), ('atacado', 'Atacado'), ('exportacao', 'Exportação'), ('especial', 'Especial'), ('funcionario', 'Funcionário')], default='varejo', max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, help_text='NULL = sem prazo', null=True)),
                ('permite_desconto', models.BooleanField(default=True)),
                ('desconto_maximo_geral', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('acrescimo_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Para tabelas com acréscimo (ex: prazo longo)', max_digits=5)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
            ],
            options={
                'verbose_name': 'Tabela de Preço',
                'verbose_name_plural': 'Tabelas de Preço',
                'db_table': 'tabelas_preco',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=6)),
                ('descricao', models.CharField(max_length=40)),
                ('tipo', models.CharField(blank=True, choices=[('unidade', 'Unidade'), ('peso', 'Peso'), ('volume', 'Volume'), ('comprimento', 'Comprimento'), ('area', 'Área')], max_length=20)),
                ('fator_conversao_base', models.DecimalField(decimal_places=6, default=1, help_text='Conversão para a unidade base da categoria (KG=1, G=0.001)', max_digits=14)),
                ('ativo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_medida', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidades_medida',
                'ordering': ['sigla'],
                'unique_together': {('empresa', 'sigla')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fator_conversao_compra', models.DecimalField(decimal_places=6, default=1, help_text='Ex: 1 caixa = 12 unidades', max_digits=14)),
                ('codigo', models.CharField(blank=True, help_text='Código interno', max_length=30)),
                ('codigo_barras', models.CharField(blank=True, help_text='EAN-13 ou DUN-14', max_length=14)),
                ('codigos_barras_extras', models.JSONField(blank=True, default=list, help_text='Array de códigos alternativos')),
                ('descricao', models.CharField(max_length=150)),
                ('descricao_completa', models.TextField(blank=True)),
                ('descricao_pdv', models.CharField(blank=True, help_text='Nome curto para PDV', max_length=80)),
                ('ncm', models.CharField(help_text='NCM errado = rejeição SEFAZ', max_length=8)),
                ('cest', models.CharField(blank=True, help_text='Obrigatório com ST', max_length=7)),
                ('cfop_venda_interna', models.CharField(blank=True, max_length=5)),
                ('cfop_venda_interestadual', models.CharField(blank=True, max_length=5)),
                ('cfop_venda_exportacao', models.CharField(blank=True, max_length=5)),
                ('cfop_devolucao', models.CharField(blank=True, max_length=5)),
                ('cfop_compra', models.CharField(blank=True, max_length=5)),
                ('origem_produto', models.SmallIntegerField(choices=[(0, '0 - Nacional'), (1, '1 - Estrangeira importação direta'), (2, '2 - Estrangeira adquirida mercado interno'), (3, '3 - Nacional, conteúdo importado 40%-70%'), (4, '4 - Nacional, processo produtivo básico'), (5, '5 - Nacional, conteúdo importado até 40%'), (6, '6 - Estrangeira sem similar nacional'), (7, '7 - Estrangeira adquirida MI sem similar'), (8, '8 - Nacional, conteúdo importado superior 70%')], default=0)),
                ('tipo_produto', models.CharField(choices=[('unitario', 'Unitário'), ('fracionado', 'Fracionado'), ('granel_peso', 'Granel (peso)'), ('granel_volume', 'Granel (volume)'), ('granel_metragem', 'Granel (metragem)'), ('servico', 'Serviço'), ('kit', 'Kit')], default='unitario', max_length=20)),
                ('codigo_balanca', models.CharField(blank=True, help_text='Código para balança (4-5 dígitos)', max_length=5)),
                ('tara_padrao', models.DecimalField(decimal_places=3, default=0, help_text='Tara em kg do recipiente padrão', max_digits=10)),
                ('variacao_peso_permitida', models.DecimalField(decimal_places=2, default=5, help_text='% variação aceita na pesagem', max_digits=5)),
                ('fracionavel', models.BooleanField(default=False)),
                ('preco_custo', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('preco_custo_medio', models.DecimalField(decimal_places=4, default=0, help_text='Calculado pelo sistema. Nunca editar manualmente.', max_digits=14)),
                ('preco_venda', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('estoque_maximo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('ponto_reposicao', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('controla_lote', models.BooleanField(default=False)),
                ('controla_validade', models.BooleanField(default=False)),
                ('dias_aviso_vencimento', models.SmallIntegerField(default=30, help_text='Avisar X dias antes do vencimento')),
                ('saida_fefo', models.BooleanField(default=True, help_text='First Expired First Out - crítico para embalagens')),
                ('permite_venda_sem_estoque', models.BooleanField(default=False)),
                ('peso_bruto', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('peso_liquido', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('largura', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('profundidade', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('localizacao_estoque', models.CharField(blank=True, help_text='Corredor/Prateleira/Posição', max_length=30)),
                ('foto_url', models.URLField(blank=True, max_length=500)),
                ('codigo_enquadramento_ipi', models.CharField(blank=True, help_text='Obrigatório quando CST IPI = 99', max_length=3)),
                ('id_externo', models.CharField(blank=True, db_index=True, max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.categoriaproduto')),
                ('classe_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.classefiscal')),
                ('filial', models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial')),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.unidademedida')),
                ('unidade_medida_compra', models.ForeignKey(blank=True, help_text='Pode comprar em caixa e vender em unidade', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos_compra', to='produtos.unidademedida')),
            ],
            options={
                'verbose_name': 'Produto',
                'db_table': 'produtos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='ClasseFiscalAliquota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf_destino', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('icms_interno', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('icms_interestadual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('icms_importado', models.DecimalField(decimal_places=2, default=4, max_digits=5)),
                ('reducao_base_icms', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tem_st', models.BooleanField(default=False)),
                ('mva_original', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mva_ajustado', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pauta_fiscal', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('icms_st', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fcp', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fcpst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fcp_retido', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tem_difal', models.BooleanField(default=False)),
                ('difal_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ipi', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pis', models.DecimalField(decimal_places=2, default=0.65, max_digits=5)),
                ('cofins', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('iss', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ibs', models.DecimalField(decimal_places=2, default=0, help_text='IBS (substitui ICMS+ISS)', max_digits=5)),
                ('cbs', models.DecimalField(decimal_places=2, default=0, help_text='CBS (substitui PIS+COFINS)', max_digits=5)),
                ('is_aliquota', models.DecimalField(decimal_places=2, default=0, help_text='Imposto Seletivo', max_digits=5)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField(blank=True, help_text='NULL = vigente até hoje', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classe_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliquotas', to='produtos.classefiscal')),
            ],
            options={
                'db_table': 'classe_fiscal_aliquotas',
                'ordering': ['classe_fiscal', 'uf_destino', '-vigencia_inicio'],
                'indexes': [models.Index(fields=['classe_fiscal', 'uf_destino', 'vigencia_inicio'], name='classe_fisc_classe__8b1e29_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemTabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preco_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('desconto_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quantidade_minima', models.DecimalField(decimal_places=3, default=0, help_text='Preço escalonado: a partir de X unidades', max_digits=12)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_tabela', to='produtos.produto')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='produtos.tabelapreco')),
            ],
            options={
                'db_table': 'itens_tabela_preco',
                'ordering': ['produto', 'quantidade_minima'],
                'unique_together': {('tabela', 'produto', 'quantidade_minima')},
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['filial', 'ativo'], name='produtos_filial__99094b_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['filial', 'codigo'], name='produtos_filial__10ab97_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['filial', 'codigo_barras'], name='produtos_filial__6fd06b_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['filial', 'descricao'], name='produtos_filial__dfe288_idx'),
        ),
    ]
