# Generated by Django 5.0.14 on 2026-05-12 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_linha_producao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='aliquota_ipi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='beneficios_fiscais_observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cfop_devolucao_compra',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='condicao_armazenamento',
            field=models.CharField(choices=[('ambiente', 'Ambiente'), ('refrigerado', 'Refrigerado'), ('congelado', 'Congelado'), ('seco', 'Seco'), ('controlado', 'Controlado')], default='ambiente', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_cofins',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_csosn',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_ipi',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='produto',
            name='cst_pis',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao_curta',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='produto',
            name='empilhamento_maximo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='especificacoes_tecnicas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_seguranca',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='produto',
            name='gera_etiqueta_balanca',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='informacoes_complementares_fiscais',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='lead_time_reposicao_dias',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='linha_producao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.linhaproducao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='margem_desejada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='produto',
            name='markup',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='produto',
            name='metodo_saida',
            field=models.CharField(choices=[('fefo', 'FEFO (First Expired First Out)'), ('fifo', 'FIFO (First In First Out)'), ('lifo', 'LIFO (Last In First Out)'), ('manual', 'Manual')], default='fefo', max_length=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='moeda',
            field=models.CharField(choices=[('BRL', 'Real (R$)'), ('USD', 'Dolar (US$)'), ('EUR', 'Euro (EUR)')], default='BRL', max_length=3),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_minimo_venda',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_minimo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_promocional',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_sugerido',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='produto',
            name='promocao_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='promocao_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_por_embalagem',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='produto',
            name='temperatura_maxima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='temperatura_minima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_embalagem',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='produto',
            name='umidade_relativa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_dimensao',
            field=models.CharField(choices=[('cm', 'Centimetro (cm)'), ('m', 'Metro (m)'), ('mm', 'Milimetro (mm)')], default='cm', max_length=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_pesagem',
            field=models.CharField(choices=[('kg', 'Quilograma (kg)'), ('g', 'Grama (g)'), ('ton', 'Tonelada (t)')], default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_peso',
            field=models.CharField(choices=[('kg', 'Quilograma (kg)'), ('g', 'Grama (g)'), ('ton', 'Tonelada (t)')], default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='vendido_por_peso_granel',
            field=models.BooleanField(default=False),
        ),
    ]
