# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0026_produto_aliquota_cbs_produto_aliquota_cofins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='rascunho_comercial',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Produto criado por entrada/XML que ainda precisa de revisao comercial antes de venda/PDV.',
            ),
        ),
    ]
