# Generated by Django 5.2.14 on 2026-06-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0028_atualizacao_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualizacaoprecoitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='atualizacaoprecolote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
