# Generated by Django 5.0.14 on 2026-05-21 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_politicareplicacaofilial_created_at_and_more'),
        ('fiscal', '0003_manifesto_config_max_nsu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestofiscalconfig',
            name='filial',
            field=models.ForeignKey(
                help_text='Filial proprietária do registro',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='core.filial',
            ),
        ),
        migrations.AlterField(
            model_name='manifestofiscaldocumento',
            name='filial',
            field=models.ForeignKey(
                help_text='Filial proprietária do registro',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='core.filial',
            ),
        ),
    ]