# Generated by Django 5.0.14 on 2026-05-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_item_entrada_custo_unitario_manual'),
        ('produtos', '0027_produto_rascunho_comercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEntradaNFProdutoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unidade_estoque', models.CharField(blank=True, max_length=10)),
                ('numero_lote', models.CharField(blank=True, max_length=60)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('custo_percentual', models.DecimalField(blank=True, decimal_places=4, help_text='Percentual opcional do custo do item da NF aplicado a este produto.', max_digits=7, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_gerados', to='compras.itementradanf')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Produto gerado da entrada',
                'verbose_name_plural': 'Produtos gerados da entrada',
                'db_table': 'itens_entrada_nf_produtos_gerados',
                'ordering': ['item', 'ordem', 'pk'],
                'indexes': [models.Index(fields=['item', 'ordem'], name='item_entrada_gerado_ord_idx'), models.Index(fields=['produto'], name='item_entrada_gerado_prod_idx')],
            },
        ),
    ]
