# Generated by Django 5.0.14 on 2026-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_item_quantidade_xml_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradanf',
            name='altera_custo_estoque',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entradanf',
            name='movimenta_estoque',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entradanf',
            name='movimenta_financeiro',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entradanf',
            name='origem_fiscal',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('importacao', 'Importacao')], db_index=True, default='nacional', max_length=20),
        ),
        migrations.AddField(
            model_name='entradanf',
            name='tipo_entrada_operacional',
            field=models.CharField(choices=[('compra_revenda', 'Compra para revenda'), ('compra_producao', 'Compra para producao'), ('uso_consumo', 'Uso e consumo'), ('ativo_imobilizado', 'Ativo imobilizado'), ('servico_despesa', 'Servico / despesa'), ('bonificacao_amostra', 'Bonificacao / amostra'), ('consignacao', 'Consignacao')], db_index=True, default='compra_revenda', max_length=30),
        ),
    ]
