# Generated by Django 5.0.14 on 2026-05-27 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0015_entradanf_altera_custo_estoque_and_more'),
        ('financeiro', '0004_centrocusto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaNFRateioFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentual', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rateios_entradas_nf', to='financeiro.centrocusto')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateios_financeiros', to='compras.entradanf')),
                ('plano_contas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rateios_entradas_nf', to='financeiro.planocontas')),
            ],
            options={
                'verbose_name': 'Rateio financeiro da entrada',
                'verbose_name_plural': 'Rateios financeiros da entrada',
                'db_table': 'entradas_nf_rateios_financeiros',
                'ordering': ['entrada', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EntradaNFAjusteFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('acrescimo', 'Acrescimo'), ('desconto', 'Desconto')], default='acrescimo', max_length=20)),
                ('descricao', models.CharField(max_length=160)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_financeiros', to='compras.entradanf')),
            ],
            options={
                'verbose_name': 'Ajuste financeiro da entrada',
                'verbose_name_plural': 'Ajustes financeiros da entrada',
                'db_table': 'entradas_nf_ajustes_financeiros',
                'ordering': ['entrada', 'created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='entradanfajustefinanceiro',
            index=models.Index(fields=['entrada', 'tipo'], name='entrada_ajuste_fin_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='entradanfrateiofinanceiro',
            index=models.Index(fields=['entrada'], name='entrada_rateio_fin_ent_idx'),
        ),
        migrations.AddIndex(
            model_name='entradanfrateiofinanceiro',
            index=models.Index(fields=['plano_contas'], name='entrada_rateio_fin_pc_idx'),
        ),
        migrations.AddIndex(
            model_name='entradanfrateiofinanceiro',
            index=models.Index(fields=['centro_custo'], name='entrada_rateio_fin_cc_idx'),
        ),
    ]
