# Generated by Django 6.0.4 on 2026-04-17 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='filial',
            field=models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial'),
        ),
        migrations.AddField(
            model_name='clienteendereco',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='cadastros.cliente'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='filial',
            field=models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial'),
        ),
        migrations.AddField(
            model_name='representante',
            name='filial',
            field=models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial'),
        ),
        migrations.AddField(
            model_name='representante',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Se o representante também é usuário do sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='filial',
            field=models.ForeignKey(help_text='Filial proprietária do registro', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.filial'),
        ),
        migrations.AddField(
            model_name='veiculotransportadora',
            name='transportadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='cadastros.transportadora'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['filial', 'ativo'], name='clientes_filial__c829d1_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['filial', 'cpf_cnpj'], name='clientes_filial__fb6e66_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['filial', 'razao_social'], name='clientes_filial__0df5e4_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['filial', 'ativo'], name='fornecedore_filial__c1a0cd_idx'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['filial', 'cpf_cnpj'], name='fornecedore_filial__227af0_idx'),
                ),
            ],
        ),
    ]
