# Generated by Django 5.0.14 on 2026-05-21 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_transportadora_representante_filiais'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                model_name='clientefilial',
                new_name='clientes_fi_filial__cb2c0a_idx',
                old_name='clientes_fi_filial_a9398f_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                model_name='clientefilial',
                new_name='clientes_fi_cliente_0b16c4_idx',
                old_name='clientes_fi_cliente_3eec06_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                model_name='fornecedorfilial',
                new_name='fornecedore_filial__64bf7f_idx',
                old_name='fornecedor_f_filial_1fa82e_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                model_name='fornecedorfilial',
                new_name='fornecedore_fornece_a33ca1_idx',
                old_name='fornecedor_f_fornece_98044f_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                model_name='representantefilial',
                new_name='representan_filial__9c8ed9_idx',
                old_name='representan_filial_641214_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                model_name='representantefilial',
                new_name='representan_represe_b468bd_idx',
                old_name='representan_represe_e92d23_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                model_name='transportadorafilial',
                new_name='transportad_filial__f5aeb0_idx',
                old_name='transportad_filial_abd7fb_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                model_name='transportadorafilial',
                new_name='transportad_transpo_a73418_idx',
                old_name='transportad_transpo_8a2d50_idx',
                ),
            ],
        ),
    ]
