# Generated by Django 6.0.4 on 2026-06-08 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cadastros",
            "0006_rename_clientes_fi_filial_a9398f_idx_clientes_fi_filial__cb2c0a_idx_and_more",
        ),
        ("core", "0024_cte"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motorista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=120)),
                ("cpf", models.CharField(blank=True, max_length=14)),
                ("rg", models.CharField(blank=True, max_length=20)),
                (
                    "cnh",
                    models.CharField(blank=True, max_length=20, verbose_name="CNH"),
                ),
                (
                    "categoria_cnh",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("AB", "AB"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("ACC", "ACC"),
                        ],
                        max_length=10,
                        verbose_name="Categoria CNH",
                    ),
                ),
                (
                    "validade_cnh",
                    models.DateField(
                        blank=True, null=True, verbose_name="Validade CNH"
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("celular", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=120)),
                ("endereco", models.CharField(blank=True, max_length=255)),
                ("cidade", models.CharField(blank=True, max_length=80)),
                (
                    "uf",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "transportadora",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="motoristas",
                        to="cadastros.transportadora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Motorista",
                "verbose_name_plural": "Motoristas",
                "db_table": "motoristas",
                "ordering": ["nome"],
                "indexes": [
                    models.Index(
                        fields=["filial", "ativo"], name="motoristas_filial__c0d982_idx"
                    )
                ],
            },
        ),
    ]
