# Generated by Django 6.0.4 on 2026-06-08 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0007_motorista"),
        ("core", "0024_cte"),
    ]

    operations = [
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("placa", models.CharField(db_index=True, max_length=8)),
                ("descricao", models.CharField(blank=True, max_length=120)),
                ("marca", models.CharField(blank=True, max_length=60)),
                ("modelo", models.CharField(blank=True, max_length=80)),
                (
                    "ano_fabricacao",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("cor", models.CharField(blank=True, max_length=40)),
                (
                    "renavam",
                    models.CharField(blank=True, max_length=15, verbose_name="RENAVAM"),
                ),
                ("chassi", models.CharField(blank=True, max_length=17)),
                (
                    "uf_placa",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="UF da placa",
                    ),
                ),
                (
                    "tipo_rodado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Truck", "Truck"),
                            ("Toco", "Toco"),
                            ("Carreta", "Carreta"),
                            ("VUC", "VUC"),
                            ("Furgão", "Furgão"),
                            ("Van", "Van"),
                            ("Moto", "Moto"),
                            ("Carro", "Carro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_carroceria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Aberta", "Aberta"),
                            ("Fechada", "Fechada"),
                            ("Graneleira", "Graneleira"),
                            ("Porta-container", "Porta-container"),
                            ("Sider", "Sider"),
                            ("Baú", "Baú"),
                            ("Cegonha", "Cegonha"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tara",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Peso tara em kg",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "capacidade_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Capacidade (kg)",
                    ),
                ),
                (
                    "capacidade_m3",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Capacidade (m³)",
                    ),
                ),
                ("observacao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                (
                    "filial",
                    models.ForeignKey(
                        help_text="Filial proprietária do registro",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.filial",
                    ),
                ),
                (
                    "transportadora",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veiculos_filial",
                        to="cadastros.transportadora",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "db_table": "veiculos",
                "ordering": ["placa"],
                "indexes": [
                    models.Index(
                        fields=["filial", "ativo"], name="veiculos_filial__7627f7_idx"
                    )
                ],
            },
        ),
    ]
