# Generated by Django 6.0.4 on 2026-06-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0008_veiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorista",
            name="bairro",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="motorista",
            name="cep",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="motorista",
            name="numero",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
