# Generated by Django 5.0.14 on 2026-05-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_item_venda_pdv_estoque_promocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivopdv',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dispositivopdv',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vendapdv',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vendapdv',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
