# Generated by Django 5.2.14 on 2026-05-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdv", "0002_venda_delivery_status"),
        ("pdv", "0004_venda_delivery_status"),
    ]

    operations = []
