# Generated by Django 5.0.14 on 2026-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomacaoRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('gatilho', models.CharField(help_text='estoque.minimo|nfe.autorizada|venda.finalizada|boleto.vencido|validade.proximo|op.encerrada|rendimento.baixo|perda.excessiva', max_length=60)),
                ('condicoes', models.JSONField(blank=True, default=dict)),
                ('acao', models.CharField(help_text='gerar_pedido_compra|baixar_conta_receber|enviar_webhook|enviar_email|bloquear_cliente|criar_ordem_producao|bloquear_lote', max_length=60)),
                ('parametros_acao', models.JSONField(blank=True, default=dict)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Regra de automação',
                'verbose_name_plural': 'Regras de automação',
                'db_table': 'automacoes_regras',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100)),
                ('valor', models.TextField(blank=True)),
                ('tipo_valor', models.CharField(default='string', help_text='string|boolean|integer|decimal|json', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configuracoes_sistema',
            },
        ),
        migrations.CreateModel(
            name='HistoricoCustoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_anterior', models.DecimalField(decimal_places=4, max_digits=14)),
                ('custo_novo', models.DecimalField(decimal_places=4, max_digits=14)),
                ('custo_medio_anterior', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('custo_medio_novo', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('motivo', models.CharField(blank=True, max_length=60)),
                ('documento_referencia_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historico_custo_produto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPrecoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_anterior', models.DecimalField(decimal_places=4, max_digits=14)),
                ('preco_novo', models.DecimalField(decimal_places=4, max_digits=14)),
                ('motivo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historico_preco_venda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegracaoExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=60)),
                ('tipo', models.CharField(blank=True, max_length=30)),
                ('endpoint_base', models.URLField(blank=True, max_length=255)),
                ('client_id', models.CharField(blank=True, max_length=200)),
                ('client_secret_encrypted', models.CharField(blank=True, max_length=500)),
                ('access_token_encrypted', models.CharField(blank=True, max_length=1000)),
                ('refresh_token_encrypted', models.CharField(blank=True, max_length=1000)),
                ('token_expira_em', models.DateTimeField(blank=True, null=True)),
                ('configuracoes_extras', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('ultima_conexao_sucesso', models.DateTimeField(blank=True, null=True)),
                ('ultima_conexao_erro', models.DateTimeField(blank=True, null=True)),
                ('mensagem_ultimo_erro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Integração externa',
                'verbose_name_plural': 'Integrações externas',
                'db_table': 'integracoes_externas',
            },
        ),
        migrations.CreateModel(
            name='LogAcessoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='login|logout|senha_errada|bloqueio|pin_pdv', max_length=20)),
                ('ip_acesso', models.GenericIPAddressField(blank=True, null=True)),
                ('device_serial', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('sucesso', models.BooleanField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de acesso',
                'verbose_name_plural': 'Logs de acesso',
                'db_table': 'analytics_log_acesso',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='LogErro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(blank=True, max_length=60)),
                ('descricao_erro', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('ip_acesso', models.GenericIPAddressField(blank=True, null=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de erro',
                'verbose_name_plural': 'Logs de erro',
                'db_table': 'log_erros',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='LogSistemaAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=60)),
                ('acao', models.CharField(max_length=30)),
                ('tabela_afetada', models.CharField(blank=True, max_length=60)),
                ('registro_id', models.BigIntegerField(blank=True, null=True)),
                ('dados_anteriores', models.JSONField(blank=True, null=True)),
                ('dados_novos', models.JSONField(blank=True, null=True)),
                ('ip_acesso', models.GenericIPAddressField(blank=True, null=True)),
                ('device_serial', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de sistema',
                'verbose_name_plural': 'Logs de sistema',
                'db_table': 'analytics_log_sistema',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ModuloAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=60)),
                ('ativo', models.BooleanField(default=False)),
                ('data_ativacao', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'modulos_ativos',
            },
        ),
        migrations.CreateModel(
            name='TravaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('motivo', models.TextField(blank=True)),
                ('modulos_travados', models.JSONField(default=list, help_text='["financeiro","fiscal","estoque","producao"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trava de período',
                'verbose_name_plural': 'Travas de período',
                'db_table': 'trava_periodos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='WebhookConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=80)),
                ('url_destino', models.URLField(max_length=500)),
                ('secret_hash', models.CharField(blank=True, max_length=255)),
                ('eventos', models.JSONField(help_text='["venda.finalizada","nfe.autorizada","estoque.minimo","op.encerrada"]')),
                ('headers_extras', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'db_table': 'webhooks_configuracao',
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=60)),
                ('payload_enviado', models.JSONField(blank=True, null=True)),
                ('codigo_http_resposta', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resposta', models.TextField(blank=True)),
                ('sucesso', models.BooleanField()),
                ('tentativa', models.PositiveSmallIntegerField(default=1)),
                ('proximo_retry_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webhooks_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
