# Generated by Django 5.0.14 on 2026-04-28 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automacaoregra',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automacoes', to='core.filial'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to='core.filial'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicocustoproduto',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.filial'),
        ),
    ]
