# Generated by Django 5.0.14 on 2026-05-21 04:55
# Ajustado para reconciliar banco legado: tabela_preco_id pode já ter sido removida.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='logsistemaanalytics',
                    new_name='analytics_l_data_ho_21d17f_idx',
                    old_name='log_sistema_data_ho_c05b35_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='logsistemaanalytics',
                    new_name='analytics_l_tabela__c5f1cd_idx',
                    old_name='log_sistema_tabela__e400aa_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE historico_preco_venda DROP COLUMN IF EXISTS tabela_preco_id;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='historicoprecovenda',
                    name='tabela_preco',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='integracaoexterna',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='integracaoexterna',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
