# Generated by Django 5.0.14 on 2026-04-28 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('estoque', '0001_initial'),
        ('producao', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome_parametro', models.CharField(max_length=60)),
                ('unidade_medida', models.CharField(blank=True, help_text='°Brix | pH | % | g/cm³ | N | mm | mPa·s | CFU/g', max_length=10)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('valor_ideal', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linha_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_qualidade', to='produtos.linhaproducao')),
            ],
            options={
                'verbose_name': 'Parâmetro de qualidade',
                'verbose_name_plural': 'Parâmetros de qualidade',
                'db_table': 'parametros_qualidade',
                'ordering': ['linha_producao', 'nome_parametro'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_analise', models.CharField(choices=[('materia_prima', 'Matéria-prima'), ('produto_acabado', 'Produto Acabado'), ('processo', 'Processo'), ('embalagem', 'Embalagem')], max_length=30)),
                ('parametros', models.JSONField(help_text='{"brix": 12.5, "ph": 3.8, "acidez": 0.65}')),
                ('resultado', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('aprovado_com_ressalva', 'Aprovado com ressalva')], default='pendente', max_length=30)),
                ('data_analise', models.DateTimeField()),
                ('laudo_pdf_url', models.URLField(blank=True, max_length=500)),
                ('observacao', models.TextField(blank=True)),
                ('acao_reprovacao', models.CharField(blank=True, choices=[('bloqueio', 'Bloqueio'), ('descarte', 'Descarte'), ('reprocessamento', 'Reprocessamento'), ('devolucao_fornecedor', 'Devolução ao fornecedor')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_qualidade', to='core.filial')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises', to='estoque.loteproduto')),
                ('ordem_producao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises', to='producao.ordemproducao')),
                ('responsavel_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análise de qualidade',
                'verbose_name_plural': 'Análises de qualidade',
                'db_table': 'analises_qualidade',
                'ordering': ['-data_analise'],
                'indexes': [models.Index(fields=['filial', 'tipo_analise', 'resultado'], name='analises_qu_filial__a685ac_idx'), models.Index(fields=['lote'], name='analises_qu_lote_id_a54546_idx')],
            },
        ),
    ]
