# Generated by Codex on 2026-05-14

import django.db.models.deletion
from django.db import migrations, models


def criar_tabela_parametro_produto(apps, schema_editor):
    if "parametros_qualidade_produtos" in schema_editor.connection.introspection.table_names():
        return
    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == "postgresql":
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS parametros_qualidade_produtos (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                    filial_id BIGINT NOT NULL REFERENCES filiais(id) DEFERRABLE INITIALLY DEFERRED,
                    produto_id BIGINT NOT NULL REFERENCES produtos(id) DEFERRABLE INITIALLY DEFERRED,
                    ativo BOOLEAN NOT NULL DEFAULT TRUE,
                    etapa VARCHAR(30) NOT NULL DEFAULT 'produto_acabado',
                    nome_parametro VARCHAR(60) NOT NULL,
                    tipo_valor VARCHAR(20) NOT NULL DEFAULT 'numero',
                    unidade_medida VARCHAR(10) NOT NULL DEFAULT '',
                    valor_minimo NUMERIC(10, 3) NULL,
                    valor_maximo NUMERIC(10, 3) NULL,
                    valor_ideal NUMERIC(10, 3) NULL,
                    valor_texto_ideal VARCHAR(120) NOT NULL DEFAULT '',
                    opcoes JSONB NOT NULL DEFAULT '[]'::jsonb,
                    obrigatorio BOOLEAN NOT NULL DEFAULT TRUE,
                    CONSTRAINT parametros_qualidade_produtos_unique
                        UNIQUE (filial_id, produto_id, etapa, nome_parametro)
                )
            """)
        else:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS parametros_qualidade_produtos (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    created_at DATETIME NOT NULL,
                    updated_at DATETIME NOT NULL,
                    filial_id BIGINT NOT NULL REFERENCES filiais(id),
                    produto_id BIGINT NOT NULL REFERENCES produtos(id),
                    ativo BOOL NOT NULL DEFAULT 1,
                    etapa VARCHAR(30) NOT NULL DEFAULT 'produto_acabado',
                    nome_parametro VARCHAR(60) NOT NULL,
                    tipo_valor VARCHAR(20) NOT NULL DEFAULT 'numero',
                    unidade_medida VARCHAR(10) NOT NULL DEFAULT '',
                    valor_minimo DECIMAL(10, 3) NULL,
                    valor_maximo DECIMAL(10, 3) NULL,
                    valor_ideal DECIMAL(10, 3) NULL,
                    valor_texto_ideal VARCHAR(120) NOT NULL DEFAULT '',
                    opcoes TEXT NOT NULL DEFAULT '[]',
                    obrigatorio BOOL NOT NULL DEFAULT 1,
                    UNIQUE (filial_id, produto_id, etapa, nome_parametro)
                )
            """)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("produtos", "0010_marca_produto_fornecedor"),
        ("qualidade", "0001_initial"),
    ]

    parametros_model = migrations.CreateModel(
        name="ParametroQualidadeProduto",
        fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("filial", models.ForeignKey(help_text="Filial propriet\u00e1ria do registro", on_delete=django.db.models.deletion.PROTECT, related_name="+", to="core.filial")),
            ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ("etapa", models.CharField(choices=[("materia_prima", "Mat\u00e9ria-prima"), ("produto_acabado", "Produto Acabado"), ("processo", "Processo"), ("embalagem", "Embalagem")], default="produto_acabado", help_text="Em qual etapa esse parametro se aplica.", max_length=30)),
            ("nome_parametro", models.CharField(max_length=60)),
            ("tipo_valor", models.CharField(choices=[("numero", "Numero"), ("texto", "Texto"), ("sim_nao", "Sim/Nao"), ("selecao", "Selecao")], default="numero", max_length=20)),
            ("unidade_medida", models.CharField(blank=True, help_text="Ex.: Brix | pH | % | g | kg | mm | C", max_length=10)),
            ("valor_minimo", models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ("valor_maximo", models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ("valor_ideal", models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ("valor_texto_ideal", models.CharField(blank=True, max_length=120)),
            ("opcoes", models.JSONField(blank=True, default=list, help_text='Lista de opcoes quando tipo_valor = "selecao".')),
            ("obrigatorio", models.BooleanField(default=True)),
            ("produto", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="parametros_qualidade_produto", to="produtos.produto")),
        ],
        options={
            "verbose_name": "Parametro de qualidade (produto)",
            "verbose_name_plural": "Parametros de qualidade (produto)",
            "db_table": "parametros_qualidade_produtos",
            "ordering": ["produto", "etapa", "nome_parametro"],
            "unique_together": {("filial", "produto", "etapa", "nome_parametro")},
        },
    )

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(criar_tabela_parametro_produto, migrations.RunPython.noop),
            ],
            state_operations=[parametros_model],
        ),
    ]
